---
forecast_id: 2026-09-09_fomc-sep-2027-below-2026_r1
question_id: fomc-sep-2027-below-2026
question_snapshot: "2026-09-16 공표되는 SEP에서 2027년말 연방기금금리 중간값이 2026년말 중간값보다 낮을 확률은?"
timestamp: 2026-09-09 17:50 KST
phase: P1
model: claude-opus-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 78
anchor_pct: 85
ci80: [64, 88]
shadow_extremized: 90
window_end: null
snapshots:
  sep_2026_06: "2026-06-17 공표 SEP Table 1 인쇄값 — 2026년말 3.8 · 2027년말 3.6 · 2028년말 3.4 · longer run 3.1. **제출 18명**(각주). 점도표 산출 실제 중간값: 2026년말 정확히 3.750 (가운데 두 점 3.625/3.875 평균), 2027년말 3.625. 따라서 2027 < 2026 = YES 형태"
  sep_2026_06_dots_2026ye: "4.375×1 · 4.125×5 · 3.875×3 · 3.625×8 · 3.375×1 = 18명. ≤3.625 9명 / ≥3.875 9명으로 **정확히 9-9 분할**"
  sep_2026_03: "2026-03-18 공표 — 2026년말 3.4(산출 3.375) · 2027년말 3.1. 제출 19명. 2027 < 2026 = YES 형태. 3월→6월 2026년말 중간값 +0.375%p 매파 이동"
  current_rate: "목표범위 3.50–3.75% (중점 3.625), 2025-12-10 이후 5회 연속 동결. longer run 중간값 3.125 — **현 정책금리가 장기 중립을 약 50bp 상회**"
  participant_parity: "6월 18명(짝수) 제출 — Atlanta 연은 총재 공석(Bostic 퇴임, 후임 지명 2026-09-09 현재 미확인)이 원인으로 추정되나 Fed 는 미제출자를 명시하지 않음 [미검증]. 9월도 18명 가능성이 높다"
  market_hike_odds: "9/16 인상 Kalshi 54.5% · Polymarket 52.5% · CME 약 56% (2026-09-09). 인하 확률 사실상 0%"
  inflation_context: "Warsh 인용 PCE 12개월 3.7% · 6개월 4.1% (잭슨홀 2026-08-28). 7월 CPI 헤드라인 3.4% · 근원 2.5%. 8월 고용 +162k, 실업률 4.1%"
  blackout: "2026-09-05 ~ 2026-09-17 — 잔여 정보는 2026-09-11 8월 CPI 하나"
market_implied: null
edge: null
sources_count: 11
---

## [0] 질문 검증

판정 가능하다. 이 질문은 **폐기된 `fomc-sep-2026ye-dot-above-375`의 대체**다.

원 질문은 "SEP 표의 2026년말 median > 3.75%"였는데, 2026-06 SEP가 표에 **3.8을 인쇄했으나 실제 중간값은 정확히 3.750**이었다(18명 제출, 가운데 두 점 3.625·3.875의 평균 — SEP 각주의 짝수 규칙). 원 질문은 "정확히 3.75%면 NO"라고 못박았으므로, **표 인쇄값을 읽는 판정자는 YES, 점도표 산출값을 계산하는 판정자는 NO**라는 정반대 결론이 나온다. 사전등록이 금지한 `ambiguous_resolution`이다. 예측 0건 상태에서 폐기했다.

이 대체 질문은 **두 중간값을 같은 규칙으로 산출해 비교**하므로 그 모호성이 소거된다. 6월 값으로 검증하면 인쇄값 비교(3.6 < 3.8)와 산출값 비교(3.625 < 3.750)가 **같은 결론(YES)**을 준다.

**예상확률은 리서치 이후 산정**이므로 사전등록의 '사전 추정 정확도' 표본에서 제외한다.

## [1] Outside View — base rate (anchor: 85%)

참조 클래스: **"정책금리가 longer-run 중간값을 상회하는 상태에서 공표된 SEP에서, 다음 해 중간값이 당해 중간값보다 낮은 경우"**. 이 조건이 중요하다 — 금리가 중립 아래에서 상승 중이면 반대 부호가 나오기 때문이다.

| SEP | 당해 vs 다음 해 중간값 | 정책금리 대 longer-run | 판정 |
|---|---|---|---|
| 2026-06 | 2026 3.750 → 2027 3.625 | 3.625 > 3.125 (상회) | **YES** |
| 2026-03 | 2026 3.375 → 2027 3.125 | 상회 | **YES** |
| 2024-12 | 2024 4.4 → 2025 3.9 | 크게 상회 | **YES** |
| 2023-12 | 2023 5.4 → 2024 4.6 | 크게 상회 | **YES** |
| **반례** 2022-12 | 2022 4.4 → 2023 5.1 | 상승 사이클 진행 중, 중립 대비 이제 막 상회 | **NO** |
| **반례** 2018-09 | 2018 2.4 → 2019 3.1 | 중립 근처에서 상승 중 | **NO** |

**구조적 이유**: SEP 점도표는 정책금리가 중립을 상회할 때 투영 기간에 걸쳐 longer-run으로 수렴하는 형태를 갖는다. 현재 3.625(중점)가 longer-run 3.125를 **약 50bp 상회**하므로 이 형태에 해당한다. 반례 두 건은 모두 "중립 근처에서 상승 사이클이 아직 진행 중"인 국면이었다.

anchor를 **85%**로 둔다.

## [2] Inside View — 보정 (항목별)

| 증거 | 방향 | 조정 |
|---|---|---|
| **6월 SEP가 이미 YES 형태였고 하향 경사가 일관된다** — 2026 3.750 → 2027 3.625 → 2028 3.375 → longer run 3.125. 네 지점이 단조 감소 | 상승 | **+2%p** |
| **간격이 한 눈금뿐이다 (핵심 하방)** — 6월의 2026-2027 격차는 0.125로 그리드 **1스텝**이다. 2027 중간값이 한 칸 오르거나 2026이 한 칸 내리면 동률이 되고, **동률은 NO**다. 여유가 최소 단위다 | 하락 | **−5%p** |
| **매파 레짐이 격차를 압축한다** — Warsh는 잭슨홀에서 PCE 12개월 3.7%·6개월 4.1%을 들며 "we have work to do"라 했고, 7월 의사록은 "several participants favored an increase"였다. 위원회가 2027년까지 이어지는 긴축을 그리면 2027 중간값이 2026과 같거나 높아질 수 있다 — 2018·2022 반례의 형태 | 하락 | **−4%p** |
| **9월 인상이 실현되면 2026년말 중간값이 밀려 올라가 격차가 오히려 벌어질 수 있다** — 인상 시 2026년말 점 대부분이 ≥3.875로 이동하는데, 2027년말 점이 같은 폭으로 따라 오르지 않으면(완화 전환을 그리면) 격차 확대 | 상승 | **+3%p** |
| **longer-run 상향 개정 리스크** — Warsh 체제가 중립금리 추정을 올리면 2027 점들이 함께 올라 격차가 좁아진다. 다만 longer-run은 6월에 3.1로 3월과 동일했고 개정 빈도가 낮다 | 하락 | **−2%p** |
| **참가자 홀짝 문제는 이 질문에 거의 무해하다** — 원 질문에서는 18명일 때만 3.750(동률)이 가능해 판정을 뒤흔들었지만, 이 질문은 **두 값의 대소 비교**라 홀짝이 양쪽에 동일하게 작용한다. 동률 위험만 소폭 남는다 | 중립 | **−1%p** |

**85 + 2 − 5 − 4 + 3 − 2 − 1 = 78%**

## [3] 분해 트리 — 9월 결정으로 조건부 분해

| 분기 | 확률 | 2027 < 2026 확률 | 근거 |
|---|---|---|---|
| **인상 (3.75–4.00)** | 0.55 | **0.82** | 2026년말 점이 ≥3.875로 밀려 올라간다. 2027에 부분 되돌림을 그리는 것이 6월 형태의 연장이고, 인상 후에는 "고점 후 완화" 서사가 더 자연스럽다 |
| **동결** | 0.45 | **0.73** | 6월의 3.750/3.625 구도가 대체로 유지되나, 격차가 1스텝뿐이라 2027 점 한두 개만 올라도 동률(NO)이 된다. 동결은 "아직 고점이 아니다"는 해석을 낳아 2027 상향 압력이 있다 |

**P(YES) = 0.55 × 0.82 + 0.45 × 0.73 = 0.451 + 0.329 = 0.780 ≈ 78%**

분해와 [2]가 78%로 일치한다.

## [4] Premortem — 크게 틀릴 이유 3가지

**1. 동률로 진다.** 6월 격차가 0.125(1스텝)뿐이다. 2027 중간값이 한 칸만 올라 2026과 같아지면 판정은 NO다. 이 질문은 "방향"이 아니라 "1스텝 이상의 방향"을 묻고 있고, 그 차이가 실패 경로의 대부분이다.

**2. 위원회가 2027년까지 긴축을 그린다.** PCE 6개월 연율이 4.1%로 12개월(3.7%)보다 높다 — 인플레가 재가속 중이라는 신호다. Warsh가 이 프레임을 유지하면 점도표가 2018·2022형(다음 해 > 당해)으로 뒤집힐 수 있다. 두 반례가 실재한다는 사실이 이 경로를 가설 이상으로 만든다.

**3. longer-run이 상향 개정된다.** 중립금리 추정이 3.1에서 3.4로 오르면 2027·2028 점들이 함께 올라 격차가 압축된다. Warsh 체제의 프레임 전환과 결합하면 동시에 온다.

세 경로 모두 "격차 압축"이라는 한 방향을 가리키고, 이미 −11%p로 계상됐다.

## [5] 데블스 애드버킷 — 반대증거 종합

- **6월 SEP의 2026년말 점도표는 정확히 9-9로 갈라졌다** (≤3.625 9명 / ≥3.875 9명). 위원회 내부 이견이 극단적이며, 이런 분열 상태에서 중간값의 안정성은 낮다. 한 사람의 이동이 중간값을 0.125~0.25 움직인다.
- **인쇄값과 산출값의 괴리가 이 SEP에 실재한다** — 6월 표의 "3.8"은 실제 3.750이었다. 이 질문은 대소 비교라 영향이 작지만, 판정자가 인쇄값만 보고 격차를 0.2(3.8 vs 3.6)로 오독하면 실제 격차(0.125)보다 여유가 커 보인다.
- **반례 base rate가 무시할 수 없다** — 2018·2022 두 사례에서 다음 해 중간값이 당해보다 높았다. 둘 다 긴축 사이클 진행 중이었고, 현재도 시장이 인상을 53~56%로 보는 국면이다.
- **표본이 작다** — 참조 클래스의 YES 사례 4건(2023-12·2024-12·2026-03·2026-06)은 대부분 완화 사이클이었다. 긴축 재개 국면의 표본은 사실상 반례 2건뿐이다. anchor 85%는 이 비대칭 위에 서 있다.
- **9월 SEP 자체가 개편될 수 있다** — Warsh는 포워드 가이던스 축소를 공언했고 커뮤니케이션 태스크포스를 운영 중이다. SEP 형식 변경이 9월에 적용되는지는 **NOT FOUND**. 형식이 바뀌어 점도표가 사라지면 판정 불능(void) 위험이 있다 — 확률은 낮게 보나 0은 아니다.

## [6] 최종 출력

- **확률: 78%** · 80% 신뢰구간 **[64, 88]**
- 시장내재: SEP 점도표 형태를 거래하는 마켓은 NOT FOUND. `market_implied`는 null.

**핵심 근거 3줄**
1. 정책금리(중점 3.625)가 longer-run(3.125)을 50bp 상회하는 국면에서 SEP는 다음 해를 낮게 그리는 것이 구조적 형태이고, 6월·3월·2024-12·2023-12가 모두 그 형태였다.
2. 6월 SEP는 2026 3.750 → 2027 3.625 → 2028 3.375 → longer run 3.125로 단조 감소했고, 9월 인상이 실현되면 2026년말이 밀려 올라가 격차가 오히려 벌어질 수 있다.
3. 그러나 격차가 **1스텝(0.125)뿐**이고 동률은 NO이며, PCE 6개월 연율 4.1%와 Warsh의 매파 프레임이 2027 점을 끌어올릴 수 있어 85%에서 78%로 내렸다.

**확률을 바꿀 관찰 지표 2개**
1. **2026-09-11 8월 근원 CPI** — 2.4% 이하면 "고점 후 완화" 서사가 강화돼 상향(+3~5%p). 2.6% 이상 재가속이면 2027 긴축 지속 전망이 늘어 하향(−5~8%p).
2. **9/16 공표 SEP의 longer-run 중간값** — 3.1에서 상향 개정되면 2027 점이 함께 올라 격차가 압축된다. 이 값은 결과와 동시에 공개되므로 사전 관측은 불가하나, 사후 분석에서 오차 원인 규명에 쓴다.

---

**P1 참고 의견 — 자금 결정의 단독 근거가 아닙니다.** (P3 게이트 미통과: 해소 7문항 / 50, Brier 0.1599)

## 출처

1. FOMC SEP 2026-06-17 (Table 1 · Figure 2 점도표) https://www.federalreserve.gov/monetarypolicy/files/fomcprojtabl20260617.pdf · HTML판 https://www.federalreserve.gov/monetarypolicy/fomcprojtabl20260617.htm
2. FOMC SEP 2026-03-18 https://www.federalreserve.gov/monetarypolicy/fomcprojtabl20260318.htm
3. FOMC 성명 2026-07-29 https://www.federalreserve.gov/monetarypolicy/files/monetary20260729a1.pdf
4. FOMC 성명 2025-12-10 (현 목표범위 도달) https://www.federalreserve.gov/newsevents/pressreleases/monetary20251210a.htm
5. FOMC Minutes 2026-07-29 https://www.federalreserve.gov/monetarypolicy/fomcminutes20260729.htm
6. Warsh 잭슨홀 연설 2026-08-28 https://www.federalreserve.gov/newsevents/speech/warsh20260828a.htm — PCE 12개월 3.7% · 6개월 4.1%
7. FOMC 회의 일정·SEP 동반 회의 표기 https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm
8. FOMC Blackout Calendar https://www.federalreserve.gov/monetarypolicy/files/fomc-blackout-period-calendar.pdf
9. 과거 SEP (2018-09 · 2022-12 · 2023-12 · 2024-12) — federalreserve.gov SEP 아카이브, 반례·정례 확인용
10. BLS CPI 2026-08-12 https://www.bls.gov/news.release/archives/cpi_08122026.htm
11. 시장내재 인상 확률 집계 (2026-09-09) https://defirate.com/prediction-markets/fed-decision-odds/ [2차 경유, 기록 전용]
