---
forecast_id: 2026-08-31_nasdaq-ath-eoy-2026_r2
question_id: nasdaq-ath-eoy-2026
question_snapshot: "NASDAQ Composite가 2026-12-31까지 일간 종가 기준 27,093.90(2026-06-02 사이클 ATH 종가)을 초과하는 날이 1일 이상 존재할 확률은?"
timestamp: 2026-08-31 14:35 KST
phase: P1
model: claude-opus-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 79
ci80: [66, 88]
window_end: null
snapshots:
  ath_threshold: "27,093.90 (2026-06-02 종가) — r1 확정, 변경 금지"
  current: "26,402.42 (2026-08-28 종가) — ATH 대비 −2.55%, 경신에 +2.62% 필요"
  remaining: "2026-12-31까지 약 85거래일"
market_implied: null
edge: null
sources_count: 29
---

## [0] 질문 검증

판정 가능. 임계 27,093.90은 등록 시점 고정이며 이후 ATH 갱신과 무관하다. 판정은 2026-12-31까지 ^IXIC 일간 종가가 이 값을 **초과하는 날이 1일 이상** 존재하는지 여부(터치형, 종점형 아님)다.

현재 26,402.42(2026-08-28)로 필요 상승폭은 **+2.62%**, 잔여 약 85거래일. r1(2026-07-10) 시점 현재가 26,206.89 대비 지수는 +0.75% 올랐고 필요폭은 −3.27%에서 −2.55%로 좁혀졌다.

## [1] Outside View — base rate (anchor: 84%)

참조군: **"8월 말에 ATH 4% 이내에 있던 해가, 연말까지 그 ATH를 종가로 경신했는가"**.

| 참조군 | 기저율 | n |
|---|---|---|
| 8월말 ATH −4% 이내 | 87.5% | 14/16 |
| 동, + 8월말 VIX < 17 (현 상태) | 85.7% | 6/7 |

결정론 모델 교차확인(터치형 배리어, 85거래일, +2.62% 필요):

| 연율변동성 | 드리프트 0% | +5% | +8% |
|---|---|---|---|
| 16.6% | 77.8% | 81.5% | 83.5% |
| 20.0% | 81.3% | 83.9% | 85.4% |
| 22.0% | 82.9% | 85.1% | 86.4% |

두 계열이 78~87%로 좁게 수렴한다. 이 질문의 본질은 **"4개월 안에 2.6% 오르는 날이 하루라도 있는가"**이며, 터치형이라 종점 분포보다 훨씬 관대하다. **anchor 84%**.

## [2] Inside View — 보정 (항목별)

| 증거 | 방향 | 조정 |
|---|---|---|
| 9월 FOMC 인상 리스크 — 인상 확률 약 56~58%(08-28~30). 고멀티플 지수의 멀티플 압축 요인이며 기저율 표본에 없는 조건 | 하락 | −5%p |
| 3개월째 ATH 미탈환 — 6/2 이후 두 차례 조정(7/29 −9.78%)을 거치며 아직 회복 못함. 저항 실증 | 하락 | −3%p |
| 시장 폭 악화 — NYSE+Nasdaq 이평 상회 51.40%(08-28, 주간 −2.40%p). 8월 후반 상승은 NVDA(8/27 +8.74%) 주도의 **좁은 랠리** | 하락 | −3%p |
| 포지셔닝·레버리지 극단 — BofA FMS 현금 3.5%, FINRA 마진부채 2026-06 사상최고(YoY +38.6%, 5월 +53.7%). 과거 45%+ 군집은 1999-2000·2007·2021에만 존재 | 하락 | −2%p |
| AI 자금조달 구조 — Alphabet Q2 FCF **−58.6억 달러**(사상 첫 마이너스), Meta FCF YoY −91%, 부채 조달 비중 9%(FY24)에서 32%(LTM)로. Oracle 5년 CDS 약 218bp 사상 최대 | 하락 | −2%p |
| 실적 모멘텀 — Q2 블렌디드 52.0%, EPS 서프라이즈 86%(5년 78%), CY2026·CY2027 EPS 12개월 연속 상향. NVDA Q3 가이던스 1,080억 달러 | 상승 | +3%p |
| 하이퍼스케일러 capex 전원 상향 — GOOGL 1,950~2,050억, AMZN 약 2,200억, META 하단 상향. **삭감한 곳이 없다** (MSFT는 리스 회계 재분류) | 상승 | +2%p |
| 금융환경·자사주 — NFCI −0.566(2021-11 이후 최완화), 2026 S&P 자사주 승인 약 1조 달러, **10월 하순 블랙아웃 해제**가 잔여 기간 안에 있음 | 상승 | +2%p |
| 미드텀 후 계절성 — 선거(11/03) 이후 구간은 4년 주기에서 역사적으로 강함 (단, 나스닥 미드텀 4분기 승률은 62%로 비미드텀 73%보다 낮아 과대평가 금지) | 상승 | +1%p |
| 필요폭이 작음 — +2.62%는 이 지수의 20일 실현변동성(16.65%) 기준 약 0.4 시그마(85거래일). 8/13 종가 26,803.03은 이미 ATH 대비 −1.07%까지 접근 | 상승 | +2%p |

순 조정 **−5%p** → 79%.

## [3] 분해 트리

| 경로 | 확률 | ATH 경신 조건부 | 기여 |
|---|---|---|---|
| 9~10월 무충격, 미드텀 랠리 정상 진행 | 0.45 | 0.95 | 43% |
| 얕은 조정(−3~7%) 후 4분기 회복 | 0.30 | 0.85 | 26% |
| 깊은 조정(−10% 터치, F2 시나리오) 후 회복 | 0.20 | 0.50 | 10% |
| 구조적 하락 전환(AI 신뢰 붕괴·정책 실수) | 0.05 | 0.05 | 0% |
| 합계 | | | **79%** |

**F2와의 정합성 점검(중요).** F2(−10% 터치) = 30%로 예측했다. 위 트리의 "깊은 조정" 경로 0.20에 4분기 이후 터치 가능성을 더하면 F2와 정합하며, 조건부 구조 `P(ATH) = P(ATH·터치)xP(터치) + P(ATH·무터치)x(1−터치)`에 실증값(터치 시 50%, 무터치 시 약 95%)을 넣으면 0.30x0.50 + 0.70x0.95 = **81.5%**로 79%와 근사한다. r1의 62%는 r2의 57% 터치 확률과 결합해도 71.5%가 나와야 해서 **내부 비정합**이었고, 이번 회차에서 교정한다.

**ML 앙상블 대비.** `ml_auto.md`(2026-07-20) F1 앙상블 74%(t5 68% / gbm 80%). 본 예측 79%와 5%p 차이로 **수렴**. ML은 6주 전 가격 기준이라 필요폭이 더 컸음에도 74%였으므로, 현재 상태에서는 상향될 여지가 있다.

## [4] Premortem — 틀릴 이유 3가지

1. **9월 인상이 멀티플 압축의 시작이었던 경우.** 근원 PCE 3.3%가 고착돼 연내 두 차례 인상 경로가 가격에 들어오면, 나스닥의 4개월 +2.6%는 오히려 낙관적 가정이 된다. 2018년 4분기에 −17%가 났고 그해 ATH 경신은 없었다.
2. **AI 자금조달이 실제로 깨지는 경우.** Alphabet FCF 마이너스 전환, 부외 약정 약 3조 달러 보도, Oracle CDS 사상 최대는 모두 같은 곳을 가리킨다. 지수 가중 상위가 곧 AI 캐펙스 익스포저라, 이 서사가 훼손되면 +2.6%가 아니라 −20%가 나오는 구조다.
3. **반대 방향 — 79%도 여전히 낮은 경우.** 실증 기저율은 87.5%, 무드리프트 GBM도 78~83%다. 내가 얹은 하락 조정(−15%p) 중 상당수(포지셔닝·마진부채·폭)는 **타이밍 정보가 거의 없는 지표**로, 수개월 앞선 신호이지 4개월 창의 방향 예측력이 검증된 바 없다. 이 조정이 과했다면 실제값은 85% 이상이다.

## [5] 최종 출력

- 최종 확률: **79%** (80% CI: 66~88%)
- 직전 대비: r1 62% → r2 79% (**+17%p**). 근거는 (1) 필요 상승폭이 −3.27%에서 −2.55%로 축소, (2) 참조군을 좁힌 실증 기저율(85.7~87.5%)과 배리어 모델(78~86%)이 모두 62%보다 크게 높음, (3) r1이 25% 가중한 "6/2가 이미 정점" 시나리오는 저장소 자체가 **[부분 미검증]·파라미터 5개월 미갱신**으로 표기한 닷컴 오버레이에 의존했고, 이번 회차에서 그 가중을 트리의 "구조적 하락 전환" 5%로 축소, (4) r1의 62%는 r2의 터치 57%와 결합 시 71.5%가 나와야 하는 **내부 비정합**이었다.
- **핵심 근거 3줄**:
  1. 터치형 질문이라 4개월 안에 하루만 +2.62%를 넘으면 되며, 8/13 종가는 이미 ATH −1.07%까지 접근했다.
  2. ATH 근접·저변동성 8월말 참조군의 실증 기저율은 85.7~87.5%, 배리어 모델도 78~86%로 수렴한다.
  3. 하향 요인은 9월 인상 리스크와 좁은 시장 폭이며, 이는 확률을 84%에서 79%로 낮출 뿐 방향을 뒤집지 못한다.
- **관찰 지표 2개**:
  1. **9/15~16 FOMC와 SEP** — 인상+2027 매파 경로면 70% 이하로 하향, 동결이면 85%로 상향.
  2. **^IXIC 26,800(8월 고점 종가) 돌파 여부** — 돌파 시 ATH까지 −1.1%만 남아 90% 이상으로 상향. 10월 말까지 미돌파면 65%로 하향.

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전).

## 출처 목록

- FRED NASDAQCOM 일별 종가 — https://fred.stlouisfed.org/series/NASDAQCOM (2026-08-28)
- FRED VIXCLS / CBOE VIX_History.csv — https://fred.stlouisfed.org/series/VIXCLS · https://cdn.cboe.com/api/global/us_indices/daily_prices/VIX_History.csv (2026-08-28)
- FOMC 성명 2026-07-29 — https://www.federalreserve.gov/newsevents/pressreleases/monetary20260729a.htm
- Warsh 잭슨홀 연설 2026-08-28 — https://www.federalreserve.gov/newsevents/speech/warsh20260828a.htm
- CNBC 9월 FOMC 인상 확률 (2026-08-28) — https://www.cnbc.com/2026/08/28/-september-fed-decision-now-a-coin-flip-as-rate-hike-odds-increase.html
- Forbes / Bill Stone 58% (2026-08-30) — https://www.forbes.com/sites/bill_stone/2026/08/30/fed-rate-hike-odds-rise-after-warshs-jackson-hole-speech/
- FactSet Earnings Insight 2026-08-28 — https://advantage.factset.com/hubfs/Website/Resources%20Section/Research%20Desk/Earnings%20Insight/EarningsInsight_082826.pdf
- NVIDIA FQ2 2027 실적 (2026-08-26) — https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-second-quarter-fiscal-2027
- Alphabet Q2 2026 실적 릴리스 (FCF −58.55억 달러) — https://s206.q4cdn.com/479360582/files/doc_news/2026/Jul/22/attachments/2026q2-alphabet-earnings-release.pdf
- Meta Q2 2026 실적 — https://investor.atmeta.com/investor-news/press-release-details/2026/Meta-Reports-Second-Quarter-2026-Results/default.aspx
- Microsoft FY26 Q4 실적·capex 회계 재분류 (2026-07-29) — https://www.microsoft.com/en-us/investor/events/fy-2026/earnings-fy-2026-q4
- FactSet "Hyperscalers tap external financing" (2026-07-23) — https://insight.factset.com/hyperscalers-tap-external-financing-as-ai-capex-outruns-cash-flow
- FINRA 마진부채 통계 — https://www.finra.org/sites/default/files/2021-03/margin-statistics.xlsx
- BofA Global Fund Manager Survey 2026년 8월 — https://finance.yahoo.com/markets/articles/investor-bullishness-surges-bofa-survey-141800790.html
- Stage Analysis 시장 폭 2026-08-28 — https://stageanalysis.substack.com/p/market-breadth-moving-averages-124
- 시카고연준 NFCI — https://www.chicagofed.org/research/data/nfci/current-data
- IFR 2644 (Oracle 5년 CDS 약 218bp) — https://www.ifre.com/topic-codes/2463896/trading-frenzy-builds-in-hyperscaler-debt-and-cds-markets
- Morgan Stanley 2026 미드텀 — https://www.morganstanley.com/insights/articles/2026-us-midterm-elections-stock-market-impact
- 저장소 내부: `data/base_rates/ml_auto.md` (F1 앙상블 74%), `forecasts/2026/2026-07-10_nasdaq-ath-eoy-2026_r1.md` (직전 62%)
- 기저율 계산: FRED NASDAQCOM 전체 이력 직접 집계 (8월말 앵커 조건부), 재현 가능
- GBM 배리어 계산: 본 회차 자체 산출, 재현 가능

**[미검증]** 표기: 부외 약정 약 3조 달러(WSJ 2026-08-27/28)는 원문 미확보·2차 출처 경유. 자사주 승인 1조 달러·Birinyi 1.55조 달러 추정은 2차 출처. 나스닥 구성종목 200일선 상회 비율은 **NOT FOUND**(NDX-100 70%+ 및 NYSE+Nasdaq 합산 51.40%만 확보).
