---
forecast_id: 2026-08-31_aapl-eps-beat-fq4-2026_r2
question_id: aapl-eps-beat-fq4-2026
question_snapshot: "Apple이 2026-10-29(장후 추정) 발표하는 FQ4 2026 실적에서 EPS가 발표 직전 컨센서스를 상회할 확률은?"
timestamp: 2026-08-31 19:50 KST
phase: P1
model: claude-opus-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 80
ci80: [67, 89]
window_end: null
snapshots:
  consensus_eps: "$1.9766 (Yahoo Finance / LSEG, n=28, 범위 $1.93~2.07, 채취 2026-08-31 KST) — 판정 기준. Investing.com $1.98 · TipRanks $1.98(n=31) · Nasdaq $1.98(n=8)로 수렴"
  consensus_outlier: "MarketBeat $1.96은 n=4에 자체 표 내부 불일치가 있어 미사용"
  consensus_revenue: "$113.55B (Yahoo/LSEG, n=28, 범위 $112.14~117.22B) — 회사 가이던스 환산 $111.7~113.7B의 **상단**"
  basis_risk: "Apple은 non-GAAP EPS를 발표하지 않고 GAAP만 낸다. 그런데 FQ3 2026에서 GAAP $2.02에 **관세 환급 $0.11**이 포함돼 CNBC/LSEG는 adjusted $1.91로 기록했다. FQ4 가이던스에도 관세 환급 약 +1%p 총이익률 효과가 재차 포함돼 **같은 wedge가 재발**한다. 컨센서스 $1.98은 LSEG/adjusted 기준"
  company_guidance: "총매출 +9~11% YoY(FX 역풍 −2.5%p 포함), 총이익률 47~48%(관세 환급 약 +1%p 포함), 영업비용 $19.1~19.4B, 실효세율 약 16.5%, iPhone 매출 mid-teens% 성장 (2026-07-30 콜)"
  report_date: "**회사 미확정**. investor.apple.com 이벤트 피드에 FY26 Q4 항목 부재. 2026-10-29는 과거 패턴(최근 6개 Q4가 모두 목요일) 기반 추정"
market_implied: null
edge: null
sources_count: 13
---

## [0] 질문 검증

판정 가능하나 **기준 불일치를 반드시 고정해야 한다.**

Apple은 non-GAAP EPS를 발표하지 않는다(GAAP만). 그런데 FQ3 2026에서 GAAP $2.02에 **관세 환급 $0.11**이 포함되면서, CNBC/LSEG는 *adjusted $1.91 vs 추정 $1.89*로 기록한 반면 Yahoo·MarketBeat·Investing.com은 실적치를 $2.02(GAAP)로 기록했다. **같은 분기 서프라이즈가 +1.6%와 +6.7%로 갈렸다.** 회사 기준 차이가 아니라 **벤더의 일회성 항목 처리 차이**다.

FQ4 가이던스에도 관세 환급 약 +1%p 총이익률 효과가 다시 포함돼 있으므로 **이 wedge는 재발한다**. 컨센서스 $1.9766은 LSEG/adjusted 기준이므로, 판정 시 **동일하게 adjusted 기준으로 대조**해야 한다. GAAP 프린트를 이 컨센서스에 직접 붙이면 인위적 beat가 나온다. 이를 스냅샷에 명기한다.

발표일은 회사 미확정이다 — investor.apple.com 이벤트 피드에 FY26 Q4 항목이 없다. Yahoo의 `isEarningsDateEstimate: false`는 회사 피드와 모순되므로 확정으로 취급하지 않는다.

r1(2026-08-03)은 `snapshots: {}`로 컨센서스를 기록하지 않았다. 이번 회차에서 벤더·기준·값을 고정한다.

## [1] Outside View — base rate (anchor: 78%)

S&P 500 EPS 컨센서스 상회율(FactSet Earnings Insight 2026-08-28): **5년 78% · 10년 76% · Q2 2026 86%**. 동률(tie)은 3%로 별도 집계되므로 strict-inequality(동률=NO) 질문에 그대로 쓸 수 있다. 단 Q3 2026 부정 가이던스 비율이 36%로 5년 평균 58%를 크게 밑돌아 **워크다운이 약하고 허들이 높다**.

AAPL 고유 이력: 최근 **8분기 전량 beat**. 컨센서스 값은 4개 제공사가 1~4센트 내로 일치(스냅샷 타이밍 차이).

## [2] Inside View — 보정 (항목별)

| 증거 | 방향 | 조정 |
|---|---|---|
| **8분기 전량 beat** — 기저율 78%보다 확실히 나은 종목 고유 실적 | 상승 | +6%p |
| **컨센서스가 하향 중** — Yahoo epsTrend 30일 전 $2.0176 → 현재 $1.9766. 최근 30일 상향 7 vs **하향 14**. 허들이 낮아지고 있다 | 상승 | +4%p |
| 수요가 예상을 앞선다 — FQ3 iPhone 매출 **+21.7%**(사상 최고 6월 분기), Cook: "수요가 우리 예상을 넘어섰다". 유럽 점유율 +9%p → 34%, 인도 +15%(전체 −14% 중) | 상승 | +3%p |
| 관세 환급 wedge가 **구조적으로 상방** — 컨센서스가 adjusted 기준인데 실제 GAAP에는 환급이 실린다. 판정 기준을 adjusted로 고정해도 회사 실적 자체는 이 항목만큼 두껍다 | 상승 | +2%p |
| **컨센서스 매출 $113.55B이 가이던스 상단**($111.7~113.7B) — 애널리스트가 이미 공격적으로 잡았다 | 하락 | −5%p |
| **공급 제약이 실재** — Cook: "매우 심각한 공급 제약, 공급망에 해결 여지가 제한적". SoC advanced node 가용성이 1차 병목이며 iPhone·Mac·iPad 3종에 걸린다. Apple은 매출 임팩트를 정량화하지 않았다 | 하락 | −3%p |
| 메모리 원가 — Parekh: 순차 총이익률 변동의 **100% 초과가 메모리 원가로 설명**. Cook은 "메모리 가격의 100년 홍수"로 표현 | 하락 | −2%p |
| **표준 iPhone 18이 이번 가을에 없다** — 2026년 가을은 Pro/Pro Max/폴더블 3종 프리미엄만이고 표준 모델은 2027년 봄. 볼륨 모델 매출이 이연된다 | 하락 | −3%p |
| 워크다운 약화(부정 가이던스 36%) | 하락 | −1%p |
| CEO 교체 — Ternus가 2026-09-01 취임, FQ4는 신임 CEO 체제 첫 분기 | 하락 | −1%p |

순 조정 **0%p** → 80%. (anchor 78% + 종목 프리미엄 +2%p)

## [3] 분해 트리

| 경로 | 확률 | 컨센 상회 조건부 | 기여 |
|---|---|---|---|
| 공급 제약이 가이던스 범위 안에서 소화 | 0.55 | 0.92 | 51% |
| 공급 제약이 매출을 가이던스 하단으로 밀지만 마진·세율이 상쇄 | 0.30 | 0.75 | 23% |
| 제약이 심화돼 매출·EPS 동반 하회 | 0.15 | 0.40 | 6% |
| 합계 | | | **80%** |

## [4] Premortem — 틀릴 이유 3가지

1. **공급 제약이 EPS까지 관통하는 경우.** Cook이 "매우 심각"이라 표현했고 회사가 임팩트를 정량화하지 않았다. 애널리스트가 이를 과소 반영한 채 매출 컨센서스를 가이던스 상단에 놓았다면, 실제는 하단이고 EPS도 미달할 수 있다. Morgan Stanley는 이미 9월 분기 Services 성장률을 12%에서 약 9.5%로 낮췄다.
2. **판정 기준이 뒤집히는 경우.** 컨센서스는 adjusted인데 채점 시 GAAP 프린트를 쓰면 인위적 beat가, 반대로 컨센서스를 GAAP 기준으로 재해석하면 인위적 miss가 난다. 이 질문의 결과가 **회사 실적이 아니라 벤더 기준 선택으로 갈릴 수 있다**.
3. **반대 방향 — 80%가 낮은 경우.** 8분기 전량 beat에 컨센서스가 30일간 순하향 중이다. 허들이 내려간 상태에서 수요는 예상을 앞선다. 85~88%가 맞을 수 있다.

## [5] 최종 출력

- 최종 확률: **80%** (80% CI: 67~89%)
- 직전 대비: r1 54% → r2 80% (**+26%p**). r1은 `snapshots: {}`로 컨센서스를 기록하지 않았고 종목 고유 실적도 반영하지 않았다. 이번 회차에서 (1) **8분기 전량 beat** 이력, (2) FactSet 기저율 78%, (3) 컨센서스가 30일간 **순하향**(허들 완화)임을 확인해 상향했다. 하방 요인(공급 제약, 매출 컨센서스가 가이던스 상단, 표준 iPhone 18 부재)은 순 조정에서 상쇄됐다.
- **핵심 근거 3줄**:
  1. 8분기 전량 beat에 FactSet 5년 기저율 78%가 더해져 방향은 분명하다.
  2. 컨센서스가 30일간 $2.0176에서 $1.9766으로 내려와(상향 7 vs 하향 14) 허들이 낮아졌다.
  3. 하방은 공급 제약과 매출 컨센서스가 가이던스 상단에 있다는 점이며, EPS 방향을 뒤집기보다 폭을 줄이는 요인이다.
- **관찰 지표 2개**:
  1. **D-1 컨센서스와 기준 확인** — $2.05 이상으로 재상향되면 70%로 하향. 동시에 판정에 쓸 기준(adjusted/GAAP)을 그때 확정해야 한다.
  2. **9~10월 아이폰 공급 관련 보도** — 리드타임 급증이나 출하 하향 보도가 나오면 −8%p 이상.

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전).

## 출처 목록

- Apple FQ3 2026 실적 8-K (매출 $109,417M, GAAP EPS $2.02에 관세 환급 $0.11 포함, 총이익률 50.1%, iPhone $54,252M) — https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000320193&type=8-K (2026-07-30)
- Apple FQ4 가이던스 (매출 +9~11%, 총이익률 47~48%, 영업비용 $19.1~19.4B, 실효세율 약 16.5%, iPhone mid-teens%) — 2026-07-30 실적 콜, CFO Kevan Parekh
- Apple Investor Relations 이벤트 피드 (FY26 Q4 항목 부재 — 발표일 회사 미확정 확인) — https://investor.apple.com
- Yahoo Finance / LSEG AAPL 컨센서스 ($1.9766, n=28, epsTrend 30일 전 $2.0176) — https://finance.yahoo.com/quote/AAPL/analysis/ (채취 2026-08-31)
- TipRanks AAPL 실적 (컨센 $1.98, n=31) — https://www.tipranks.com/stocks/aapl/earnings
- Investing.com AAPL 실적 (컨센 $1.98, 매출 $113.34B) — https://www.investing.com/equities/apple-computer-inc-earnings
- Nikkei Asia 2026-07-02 (2026년 가을 프리미엄 3종 집중, 표준 iPhone 18은 2027 상반기) — https://asia.nikkei.com
- Counterpoint Research 2026-08-04 (Pro·폴더블 패널 7월 출하 개시, 베이스 모델 패널 미개시) / 2026-08-20 (유럽·인도 점유율) — https://www.counterpointresearch.com
- TrendForce 2026-08-10 (iPhone 18 Pro 256GB BOM 원가 전년비 +38%, 메모리 BOM 비중 약 34%) — https://www.trendforce.com
- IDC 2026-08-26 (NAND·DRAM 원가 전년비 +300% 초과, 2026년 스마트폰 출하 −16.7%) — https://www.idc.com/resource-center/blog/smartphone-shipments-set-for-record-16-7-drop-in-2026-as-the-memory-crisis-hits-full-force/
- FactSet Earnings Insight 2026-08-28 — https://advantage.factset.com/hubfs/Website/Resources%20Section/Research%20Desk/Earnings%20Insight/EarningsInsight_082826.pdf
- 저장소 내부: `forecasts/2026/2026-08-03_aapl-eps-beat-fq4-2026_r1.md` (직전 54%, snapshots 없음)

**[미검증]** 표기: 발표일 2026-10-29는 회사 미확정이며 Yahoo의 confirmed 플래그는 Apple 자체 피드와 모순된다. Ming-Chi Kuo(2026-08-10)와 Tim Culpan(2026-08-06)의 TSMC 재공품 관련 주장이 정면 충돌해 어느 쪽도 채택하지 않았다. Calendar Q2 2026 Apple 출하 증가율이 출처별 +3%(Counterpoint 미디어 인용) vs +13%(Counterpoint 자사 트래커) vs +15.3%(IDC)로 갈리는데, Apple 실적(매출 +21.7%, ASP +8%)과 정합하는 것은 +13~15%다. 프리오더·발매일은 2026-08-31 현재 미발표.
