---
forecast_id: 2026-08-31_googl-eps-beat-2026q3_r1
question_id: googl-eps-beat-2026q3
question_snapshot: "Alphabet이 2026-10-28(장후 추정) 발표하는 Q3 2026 실적에서 EPS가 발표 직전 컨센서스를 상회할 확률은?"
timestamp: 2026-08-31 16:50 KST
phase: P1
model: claude-opus-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 83
ci80: [68, 92]
window_end: null
snapshots:
  consensus_eps: "$3.01 (Yahoo Finance, n=42, 범위 $2.64~3.68, 채취 2026-08-31 KST) — 판정 기준. 애널리스트 수와 분산을 공개하는 유일한 제공사"
  consensus_vendor_spread: "Investing.com $3.02 · TipRanks $3.02 · AlphaQuery $2.93 · MarketBeat $2.77. 스프레드 9%로 4개 메가캡 중 가장 넓다"
  consensus_revenue: "$126.66B (Investing.com)"
  company_guidance: "매출·EPS 가이던스 미제시(Alphabet 관행). capex만 2026년 $195~205B로 상향 제시 (2026-07-22)"
  basis_risk: "Alphabet은 GAAP EPS를 보고하고 컨센서스는 pro-forma 기준이라 **기준 불일치**가 존재. Q2 2026 GAAP $9.11 중 $6.26이 지분증권 미실현이익($98B)이었고, 이를 제외한 실질은 약 $2.85로 사실상 부합 수준"
  report_date: "미확정 — Wall Street Horizon 2026-10-28 UNCONFIRMED, TipRanks·Investing.com 10-27"
market_implied: null
edge: null
sources_count: 12
---

## [0] 질문 검증

판정 가능하나 **기준 불일치 리스크를 명시해야 한다.** Alphabet은 GAAP diluted EPS를 보고하는데 컨센서스는 pro-forma 성격이라, 집계사들이 "GAAP actual vs pro-forma consensus"를 비교하며 서프라이즈를 산출한다. Q2 2026이 극단적 사례다 — GAAP $9.11 vs 컨센 $2.88로 +214%가 찍혔지만, **$6.26이 지분증권 미실현이익 $98B에서 온 것**이고 이를 빼면 약 $2.85로 사실상 부합이었다.

이 구조는 **비대칭이 아니라 양방향**이다. 보유 지분(사적 AI 기업 포함)이 평가익이면 GAAP EPS가 부풀고, 평가손이면 컨센서스를 밑돌 수 있다. 질문이 "발표 EPS"로만 규정돼 있으므로 발표 헤드라인 EPS(GAAP)를 기준으로 판정하되, 이 취약성을 [2]·[4]에 반영한다.

컨센서스는 **$3.01(Yahoo, n=42)**로 고정한다 — 애널리스트 수와 범위($2.64~3.68)를 공개하는 유일한 제공사다. MarketBeat $2.77은 자체 상단($2.99)이 Yahoo 평균보다 낮아 다른 패널을 쓰는 것으로 보인다.

## [1] Outside View — base rate (anchor: 78%)

S&P 500 EPS 컨센서스 상회율(FactSet Earnings Insight 2026-08-28): **5년 평균 78% · 10년 평균 76% · Q2 2026 86%**(2021년 이후 최고). FactSet은 동률(tie)을 3%로 **별도 집계**하므로 이 수치는 이미 strict inequality 기준이며, 동률=NO인 본 질문에 그대로 쓸 수 있다.

두 가지 주의를 [2]에 반영한다. (1) Q3 2026 부정 가이던스 비율이 **36%**로 5년 평균 58%를 크게 밑돈다 — 워크다운이 약해 **다음 분기 허들이 높아졌다**. (2) 총계 서프라이즈 +26.5%는 Alphabet(지분증권 미실현이익 $98B)·Amazon($53.4B) 회계 아티팩트이며 제외 시 +10.8%, Mag 7은 +66.2%에서 **+4.4%**로 떨어진다.

GOOGL 고유 이력: 명목상 8분기 8/8 비트이나 **깨끗한 분기는 약 5개**(Q2 2026·Q1 2026·Q1 2025는 지분평가익 왜곡). 깨끗한 분기 평균 서프라이즈 약 +11.6%.

## [2] Inside View — 보정 (항목별)

| 증거 | 방향 | 조정 |
|---|---|---|
| 깨끗한 분기 기준으로도 전승, 평균 +11.6% — 영업 실적 자체가 강하다 | 상승 | +4%p |
| Q2 2026 영업이익 $40.8B(+30%), 영업이익률 34%(+2%p), 클라우드 +82% — 본업 모멘텀 확실 | 상승 | +3%p |
| **기준 불일치가 구조적으로 YES에 유리** — GAAP EPS에 지분평가익이 실리면 pro-forma 컨센서스를 쉽게 넘는다. 사적 AI 기업 밸류에이션이 상승 국면(OpenAI $852B 등)이면 Q3에도 반복될 소지 | 상승 | +4%p |
| **컨센서스 분산이 매우 넓다**($2.64~3.68, 스프레드 9%) — 애널리스트들이 지분평가익을 어떻게 처리할지 합의하지 못한 상태. 어느 값이 판정 기준이 되느냐에 결과가 갈릴 수 있다 | 하락 | −4%p |
| 지분평가익의 **양방향성** — 3분기(7~9월) 중 AI 사모 밸류에이션이나 보유 상장주가 하락하면 GAAP EPS가 역으로 눌린다. Q2의 +$6.26이 −로 뒤집히는 시나리오 | 하락 | −3%p |
| FCF −$5.9B(사상 첫 마이너스 분기), capex $195~205B로 상향 — 감가상각 증가가 EPS를 잠식하는 방향 | 하락 | −2%p |
| 워크다운 약화 | 하락 | −1%p |

순 조정 **+1%p** → 83%. (anchor 78% + 종목 프리미엄 +4%p + 순조정 +1%p)

## [3] 분해 트리

| 경로 | 확률 | 비트 조건부 | 기여 |
|---|---|---|---|
| 본업 호조 + 지분평가익 플러스 | 0.55 | 0.97 | 53% |
| 본업 호조 + 지분평가 중립 | 0.25 | 0.80 | 20% |
| 본업 호조 + 지분평가익 마이너스 | 0.15 | 0.55 | 8% |
| 본업 둔화(광고·클라우드) | 0.05 | 0.30 | 2% |
| 합계 | | | **83%** |

이 질문의 확률 대부분은 **본업이 아니라 지분평가 항목**이 결정한다. 본업만 보면 90% 이상이지만, GAAP EPS에 실리는 마크투마켓이 분기당 EPS의 두 배를 넘나드는 변동성을 만든다.

## [4] Premortem — 틀릴 이유 3가지

1. **지분평가손이 나는 경우.** Q2에 +$6.26을 만든 그 항목이 −로 돌면 GAAP EPS가 컨센서스를 크게 밑돈다. 3분기 중 AI 사모 밸류에이션 조정이나 보유 상장주 급락이 있었다면 이 시나리오가 현실화된다. 나스닥은 7/29에 −9.78% 조정을 겪었다.
2. **컨센서스 벤더 선택이 결과를 바꾸는 경우.** $2.77(MarketBeat)과 $3.02(Investing) 사이에서 실제값이 나오면 벤더에 따라 판정이 뒤집힌다. 스냅샷을 Yahoo $3.01로 고정했지만, 해소 시 다른 값이 인용되면 분쟁 소지가 있다.
3. **반대 방향 — 83%가 낮은 경우.** 명목 8/8에 깨끗한 분기도 전승이고, 기준 불일치는 구조적으로 YES 쪽에 유리하다. 지분평가익이 최근 추세대로 플러스면 90% 이상이 맞다.

## [5] 최종 출력

- 최종 확률: **83%** (80% CI: 68~92%)
- **핵심 근거 3줄**:
  1. 본업은 강하다 — Q2 영업이익 +30%, 영업이익률 34%, 클라우드 +82%로 깨끗한 분기 기준으로도 전승이다.
  2. **GAAP EPS vs pro-forma 컨센서스라는 기준 불일치**가 구조적으로 YES에 유리하나, 지분평가 항목은 양방향이라 분산을 크게 키운다.
  3. 컨센서스 제공사 스프레드가 9%로 4개 메가캡 중 가장 넓어 CI를 넓게 잡았다.
- **관찰 지표 2개**:
  1. **3분기 중 AI 사모·상장 보유지분 밸류에이션 방향** — 유의한 하락이 있으면 70% 이하로 하향.
  2. **D-1 컨센서스 수렴도** — 제공사 스프레드가 5% 이내로 좁혀지고 값이 $3.10 이상이면 허들 상승으로 −5%p.

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전).

## 출처 목록

- Alphabet Q2 2026 실적 릴리스 (매출 $119.8B, 영업이익 $40.8B, GAAP EPS $9.11, 지분증권 순이익 $98.0B, FCF −$5.9B) — https://s206.q4cdn.com/479360582/files/doc_financials/2026/q2/2026q2-alphabet-earnings-release.pdf (2026-07-22)
- CNBC Alphabet Q2 2026 — https://www.cnbc.com/2026/07/22/google-earnings-q2-goog-live-updates.html
- Yahoo Finance GOOGL 컨센서스 ($3.01, n=42, 범위 $2.64~3.68) — https://finance.yahoo.com/quote/GOOGL/analysis/ (채취 2026-08-31)
- Investing.com GOOGL 실적 ($3.02, 매출 $126.66B) — https://www.investing.com/equities/google-inc-earnings
- MarketBeat GOOGL 실적 ($2.77) — https://www.marketbeat.com/stocks/NASDAQ/GOOGL/earnings/
- Wall Street Horizon GOOGL 캘린더 (2026-10-28 UNCONFIRMED) — https://www.wallstreethorizon.com/alphabet-earnings-calendar
- FRED NASDAQCOM (7/29 −9.78% 조정 — 지분평가 리스크 맥락) — https://fred.stlouisfed.org/series/NASDAQCOM
- FactSet Earnings Insight 2026-08-28 (비트율 86%/78%/76%, 동률 3%, Q3 부정 가이던스 36%, Mag7 ex-2종목 +4.4%) — https://advantage.factset.com/hubfs/Website/Resources%20Section/Research%20Desk/Earnings%20Insight/EarningsInsight_082826.pdf
- Warsh 잭슨홀 연설 2026-08-28 — https://www.federalreserve.gov/newsevents/speech/warsh20260828a.htm

**[미검증]** 표기: 발표일 회사 미확정. Q1 2026·Q1 2025의 지분평가익 왜곡 여부는 Q2 2026 사례로부터의 추정이며 해당 분기 릴리스 원문 직접 확인은 하지 못했다 — **[부분 미검증]**. OpenAI $852B 밸류에이션은 2차 출처 경유 **[미검증]**.
