---
forecast_id: 2026-07-08_soxx-eoy-down15_r1
question_id: soxx-eoy-down15
question_snapshot: "SOXX의 2026년 마지막 거래일 종가가 기준가(첫 예측 실행일의 직전 거래일 종가) 대비 −15% 이하일 확률은?"
timestamp: 2026-07-08 10:09 KST
phase: P0
model: claude-fable-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 22
ci80: [12, 35]
window_end: null
snapshots:
  reference_price: "$551.69 (2026-07-07 종가, stockanalysis.com) — 이후 변경 금지"
  threshold: "$468.94 (= $551.69 x 0.85)"
  context: "기준가는 7/6~7 이틀 −12.9% 급락(삼성 실적발 차익실현) 직후 값. ATH $655.95 (2026-06) 대비 이미 −15.9% — 임계값은 ATH 대비 −28.5%에 해당"
market_implied: null
edge: null
sources_count: 43
research_agents: "종합 1 + 데블스 애드버킷 1 (병렬)"
---

## [0] 질문 검증

기준가 스냅샷 확정: **$551.69** (2026-07-07 종가) → YES = 2026년 최종 거래일 SOXX 종가 ≤ **$468.94**. registry notes 갱신. 진행.

## [1] Outside View — base rate (anchor: 20%)

참조 클래스: "^SOX 7월 초 종가 → 12월 말, −15% 이상 하락 유지" (종합 에이전트가 Yahoo Finance 일간 데이터로 직접 계산, 1994~2025 = 32년)

| base rate | 값 | 상세 |
|---|---|---|
| 연말까지 −15% 유지 | **6/32 = 19%** | 1995(−17.7%), 2000(−51.2%), 2001(−17.9%), 2002(−21.3%), 2007(−19.3%), 2008(−42.0%) |
| 동, 2008년 이후 | **0/17 = 0%** | 딥 바잉 레짐에서 소멸한 사건 |
| H2 중 일시적 −15% 드로다운 | 14/32 = 44% | 발생은 흔하나 연말 지속은 6/14 ≈ 43% |
| 폭등년 조건부 (7월까지 +50%↑) | 2/8 ≈ 25% | YES: 1995·2000 / NO: 1999·2003·2009·2017·2021·2024 |

가장 유사한 아날로그는 **1995년** (메모리 슈퍼사이클 H1 급등 → DRAM 가격 정점과 함께 H2 −17.7%). 2026 상반기 +101%는 1999년 이후 최고 반기 — 폭등년 조건부(25%)와 무조건부(19%)를 절충, 최근 레짐(0/17)으로 하향 → anchor **20%**.

## [2] Inside View — 보정 (20% → 24%)

| 증거 | 방향 | 조정 |
|---|---|---|
| 메모리 가격 정점 Q3~Q4 2026 컨센서스 — SOXX 최대 편입종목이 MU(8.16%), 1995년 경로의 재현 조건 성립 | ↑ | +4%p |
| 연준 인상 사이클 개시 임박 (본 시스템 FOMC 예측 48%, 연내 시장가격 >75%) — 듀레이션 자산화된 섹터의 리레이팅 리스크. 인상 원인이 메모리發 인플레라 **같은 충격이 반도체를 두 번 때리는 상관 구조** | ↑ | +3%p |
| 크라우딩 취약성 실증: 6/5 Broadcom 쇼크 하루 $1.3조 증발, 7/6~7 −12.9% — 촉매 한 번에 −10%가 두 번 재현됨 | ↑ | +2%p |
| 펀더멘털 초강세: 5월 매출 YoY +104%, 공급 2027년까지 완판, $725B 캐펙스 계약·착공 완료 — 분석가 다수 "밸류에이션 리셋" 규정 | ↓ | −3%p |
| 임계값이 ATH −28.5% — 역사적으로 2000·2008급에서만 발생한 깊이 | ↓ | −2%p |

## [3] 분해 (2단계 — 발생 x 지속)

```
YES = P(H2 중 기준가 대비 −15% 드로다운 발생) x P(연말까지 지속 | 발생)
├─ 발생: base 44% + 레짐 취약성(메모리 정점·연준·크라우딩) 상향 ≈ 55%
├─ 지속: 역사 6/14 ≈ 43% (10~12월 발생 드로다운은 연내 회복 시간 부족)
└─ 결합: 0.55 x 0.43 ≈ 24%
```

3단계 분해(촉매→깊이→지속)는 이중 차감으로 10%가 나왔으나, 역사 데이터가 직접 주는 2단계 구조가 우월 — 24% 채택, [2]와 일치.

## [4] Premortem — 이 예측이 크게 틀렸다면

1. **레짐 무시 (하방 오류)**: 2008년 이후 0/17 — "딥 바잉 + 구조적 AI 수요" 레짐에서는 −15% 지속이 소멸한 사건일 수 있음. −2%p 반영.
2. **상관 충격 과소평가 (상방 오류)**: 메모리 정점·연준 인상·AI 소화가 독립이 아니라 하나의 인플레-긴축 연쇄라면 꼬리가 두꺼움 — [2]에서 +3%p로 이미 반영.
3. **기준가 착시**: 스냅샷이 급락 직후라 통상 반등 시 YES가 더 어려워지는 기계적 구조 — 수치에 내재, 추가 조정 없음.

최종: 24% − 2%p = **22%**.

## [5] 최종 출력

- **최종 확률: 22%** (80% CI: 12~35%)
- **핵심 근거 3줄**:
  1. 역사 base rate 19% (32년), 폭등년 조건부 25% — 단 2008년 이후 0회라는 레짐 변화가 하방 견제.
  2. 상향 요인의 동시성: 메모리 가격 정점(Q3~Q4)·연준 인상 개시·실증된 크라우딩 취약성(6월·7월 −10%대 급락 2회)이 모두 윈도우 안.
  3. 임계값 $468.94는 ATH 대비 −28.5% — 2000·2008급 깊이라는 점이 확률을 20%대에 묶음.
- **관찰 지표 2개**:
  1. 8~9월 DRAM/NAND 스팟가격 롤오버 (MU 질문과 공유 지표) — 정점 확인 시 1995년 경로 개연성 급등, 확률 상향.
  2. 10월 말 하이퍼스케일러 실적의 2027 캐펙스 가이던스 + NVDA 8/26 — 캐펙스 감속 신호 시 상향.
- **액션 연결**: "레버리지 유지/축소 판단" 트리거. 22%는 낮지 않은 확률 — **VIX 조기경보(다음 예측)와 결합해 레버리지 축소의 선행 지표로 모니터링**. 하드 룰은 그대로.

> **P0 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트 통과 전).

## 출처

증거 부록(`_r1_evidence.md`) 참조. 핵심: stockanalysis.com (기준가·보유종목), Yahoo Finance ^SOX 일간 데이터 직접 계산 (base rate — 재현 가능), SIA (5월 매출 +104%), TrendForce·SK하이닉스 (메모리 정점 Q3~Q4), kavout (베어 케이스 ~20% 컨센), Benzinga·247wallst (7/6~7 급락), Morgan Stanley·Forbes (캐펙스/매출 갭).
[미검증]: P/E 59.28 vs 28.59 출처 간 불일치 (산정방식 차이), 1995~2024 폭등년 조건부는 연도 분류에 판단 개입.
