---
forecast_id: 2026-08-31_vix-25-90d_r3
question_id: vix-25-90d
question_snapshot: "예측일로부터 90일(달력일) 이내에 VIX 지수가 종가 기준 25.00을 1회 이상 상회할 확률은?"
timestamp: 2026-08-31 15:15 KST
phase: P1
model: claude-opus-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 36
ci80: [22, 52]
window_end: '2026-11-29'
snapshots:
  threshold: "VIX 일간 종가 > 25.00"
  window: "2026-08-31 ~ 2026-11-29 (90 달력일)"
  current: "14.43 (2026-08-28 종가, CBOE) — 1990년 이후 27.6분위"
  ytd_context: "2026년 25+ 종가는 이란전쟁 국면(2026-02~04)에 14일. 06-01 이후 최고 종가 22.22(06-10), 7월 조정 정점 20.66(07-29), 8월 최고 16.50(08-04)"
market_implied: null
edge: null
sources_count: 24
---

## [0] 질문 검증

판정 가능. rolling 90일 질문이므로 이번 회차의 윈도우는 **2026-08-31 ~ 2026-11-29**로 확정한다. 판정은 이 구간에 CBOE 공식 VIX **일간 종가**가 25.00을 초과하는 날이 1일 이상 존재하는지 여부다.

현재 VIX 14.43(2026-08-28 CBOE 종가). 윈도우 안에 9/15~16 FOMC(SEP 포함), 10/27~28 FOMC, **11/03 미드텀 선거**가 들어간다. 12/8~9 FOMC는 윈도우 밖이다.

## [1] Outside View — base rate (anchor: 33%)

저장소 `data/base_rates/volatility.md`의 기존 값과 이번 회차에서 정량화한 조건부를 함께 쓴다.

| 참조군 | 기저율 | n | 출처 |
|---|---|---|---|
| 90일 윈도우 무조건부 (2010~2025) | 44% | 7/16 | 기존 base_rates |
| 시점 VIX < 16 (현 상태) | 22% | 2/9 | 기존 base_rates |
| 8월말 앵커·전 연도 전체(1990~2025) | 50.0% | 18/36 | 본 회차 산출 |
| 8월말 VIX < 16 | 20.0% | 3/15 | 본 회차 산출 |
| **8월말 VIX < 16 + 직전 12개월 25+ 돌파 이력 (현 상태)** | **33.3%** | 2/6 | 본 회차 산출 |
| 8월말 VIX < 16 + 직전 12개월 무돌파 | 11.1% | 1/9 | 본 회차 산출 |

기존 base_rates 파일이 "이미 당해 연도에 25+를 찍은 해의 조건부는 더 높을 것 — **정량화 미완**"으로 남겨둔 항목을 이번 회차에서 채웠다. 연도 단위에서 **33.3% vs 11.1%**로 방향이 확인된다(n=6/9로 표본은 작다).

**레짐 불안정성이 가장 큰 caveat다.** 동일한 VIX 12~16 조건부가 10년 단위로 1990년대 0.9% → 2000년대 8.7% → 2010년대 25.6% → 2020년대 48.8%로 약 50배 벌어진다. 1990년 이후 독립적인 VIX 스파이크 군집이 약 40개(연 1.09회)뿐이라 어떤 좁은 구간도 방어되지 않는다.

**anchor 33%** — 현 상태에 가장 잘 맞는 조건부(33.3%)를 채택하되, 2020년대 레짐(48.8%)과 저변동 조건(20~22%) 사이에서 전자를 상방 리스크, 후자를 하방 리스크로 [2]에서 처리한다.

## [2] Inside View — 보정 (항목별)

| 증거 | 방향 | 조정 |
|---|---|---|
| 9월 FOMC 인상 리스크 — 잭슨홀(08-28) 후 인상 확률 약 56~58%. **인하가 아닌 인상 사이클 재개**는 기저율 표본에 사실상 없는 조건이며, VIX 스파이크의 고전적 촉매 | 상승 | +6%p |
| 실현 > 내재 — NDX 20일 실현 16.65% vs VIX 14.43(−2.14p). 옵션시장이 이미 발생한 변동성보다 낮게 가격 중 | 상승 | +3%p |
| 2020년대 레짐 — 동일 조건 10년 조건부가 48.8%. 최근 14개 분기 중 약 8개 분기에서 25+ 돌파(기존 base_rates, 고빈도 레짐) | 상승 | +3%p |
| 이벤트 밀집 — 윈도우 안에 FOMC 2회 + 미드텀 선거(11/03) + 9/30 Micron·10월 빅테크 실적 | 상승 | +2%p |
| 정책 충돌 리스크 — 재무부의 장기물 바이백 확대(9/09부터 최대 40억 달러)와 Fed 긴축 기조가 상충. 기저율이 없는 제도적 tail | 상승 | +2%p |
| **저변동 레짐의 직접 반증** — 7월 −9.78% 나스닥 드로다운에도 VIX 최고 종가 **20.66**. 06-01 이후 최고도 22.22. 즉 이 레짐은 −10%급 조정을 25 미만으로 소화한 실증이 있다 | 하락 | −8%p |
| 출발점이 매우 낮음 — 14.43은 1990년 이후 27.6분위. 25까지 **+73%** 상승이 필요하며, 8월 최고 종가는 16.50에 그침 | 하락 | −4%p |
| 기간구조 콘탱고 — VIX/VIX3M 0.826(2026-08-27). 스트레스 신호 없음 | 하락 | −1%p |
| 금융환경 완화 — NFCI −0.566(2021-11 이후 최완화), HY OAS 2.63%. 크레딧에서 전이되는 변동성 경로가 닫혀 있음 | 하락 | −1%p |

순 조정 **+2%p** → 35%. 미드텀 조건부(8월말 VIX<16 + 미드텀 = 50%, n=4)를 소폭 반영해 **36%**로 마무리한다.

## [3] 분해 트리

| 촉매 | 발생 확률 | VIX 25+ 종가 조건부 | 기여 |
|---|---|---|---|
| 9/15~16 FOMC 인상 + 매파 SEP | 0.56 | 0.30 | 17% |
| 지표 충격(9/4·10/2 NFP, 9/11·10/14 CPI) | 0.35 | 0.20 | 7% |
| 미드텀(11/03) 결과 불확실성 | 0.20 | 0.15 | 3% |
| AI 크레딧·자금조달 이벤트 | 0.15 | 0.40 | 6% |
| 지정학(호르무즈 재확대) | 0.10 | 0.35 | 4% |
| 중복 보정 | | | −1%p |
| 합계 | | | **36%** |

**F2(나스닥 −10% 터치, 30%)와의 정합.** 두 질문은 같은 하방 사건을 다른 임계로 본다. 다만 7월 실증(−9.78% 드로다운 / VIX 20.66)이 보여주듯 이 레짐에서는 **나스닥 −10%가 VIX 25를 함의하지 않는다**. F2 윈도우(9~10월)가 본 윈도우(8/31~11/29)에 포함되면서 미드텀까지 더 담기므로 36% > 30%인 것은 정합적이다.

**ML 앙상블 대비.** `ml_auto.md`(2026-07-20) VIX 앙상블 27%(t5 4% / gbm 51% — **모델 불일치 플래그**). 본 예측 36%와 9%p 차이로 divergence 임계(15%p) 미만. 다만 두 모델이 47%p 벌어져 있어 앙상블 중앙값의 정보량이 낮고, 파일 자체가 "VIX에 대한 GBM은 평균회귀를 무시한 참조치"라고 고지한다. 참고선으로만 취급한다.

## [4] Premortem — 틀릴 이유 3가지

1. **9월 인상이 실제로 나오고 시장이 이를 정책 실수로 읽는 경우(36%가 낮음).** 고용이 −23,000인 상태에서 인상하면 성장 충격과 정책 충격이 겹친다. 2018년 2월·10월 사례처럼 저변동에서 출발해도 VIX는 며칠 만에 25를 넘긴다. 이 경우 50% 이상이 맞다.
2. **저변동 레짐 반증을 과대 적용한 경우(36%가 낮음).** 7월에 VIX가 20.66에 그친 것은 하락이 **질서 있게** 진행됐기 때문이다. 강제매도(CTA −3%/−5% 트리거)가 개입하는 무질서한 하락이면 같은 낙폭에도 VIX는 훨씬 높이 튄다. 저변동 자체가 레버리지를 키워 **다음 충격의 진폭을 키운다**는 해석이 맞다면 36%는 낮다.
3. **반대 방향 — 이벤트 촉매를 과대평가한 경우(36%가 높음).** 인상은 이미 56~58% 가격에 반영돼 있어 **서프라이즈가 아니다**. 예고된 이벤트는 VIX를 잘 띄우지 못한다(2026년 25+ 돌파 14일은 전부 예고 없던 이란전쟁 국면). 조건부 기저율 하단(20~22%)이 맞다면 실제값은 25% 부근이다.

## [5] 최종 출력

- 최종 확률: **36%** (80% CI: 22~52%)
- 직전 대비: r2 42% → r3 36% (**−6%p**). 근거는 (1) VIX 출발점이 16.7에서 **14.43**으로 낮아져 25까지 +73%가 필요, (2) 7월 −9.78% 드로다운을 **20.66**으로 소화한 저변동 레짐의 직접 반증이 확보됨, (3) 반대로 9월 인상 리스크(약 56~58%)라는 r2 시점에 없던 촉매가 생겨 하락폭을 제한. 기존 base_rates의 "정량화 미완" 항목(직전 12개월 25+ 돌파 이력 조건부)을 33.3%로 채워 앵커를 교체한 것이 이번 회차의 방법론적 변화다.
- **핵심 근거 3줄**:
  1. 현 상태(8월말 VIX<16 + 직전 12개월 25+ 돌파 이력)의 조건부 기저율은 33.3%이며, 무조건부 50%와 저변동 조건 20%의 사이다.
  2. 7월 나스닥 −9.78% 조정에도 VIX 최고 종가가 20.66에 그친 것은 이 레짐이 하락을 저변동으로 소화한다는 직접 증거다.
  3. 상방은 거의 전부 9월 FOMC 인상 리스크이나, 인상이 이미 56~58% 가격에 반영돼 서프라이즈 성격이 약하다.
- **관찰 지표 2개**:
  1. **VIX 기간구조 역전 여부(VIX/VIX3M > 1.0)** — 현재 0.826. 역전 시 스트레스 국면 진입으로 55% 이상 상향.
  2. **9/15~16 FOMC 직후 5거래일 VIX 최고 종가** — 20을 넘기면 잔여 윈도우 기준 50%로 상향, 17 미만이면 20%로 하향.

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전). 이 질문은 사용자의 VIX 25+ 하드룰과 연결되나, **하드룰은 확률과 무관하게 기계적으로 유지**된다. 본 예측은 조기경보 참고치이지 룰의 대체가 아니다.

## 출처 목록

- CBOE VIX_History.csv (2026-08-28 종가 14.43, 8월 최고 16.50, 7/29 20.66, 6/10 22.22) — https://cdn.cboe.com/api/global/us_indices/daily_prices/VIX_History.csv
- FRED VIXCLS — https://fred.stlouisfed.org/series/VIXCLS (2026-08-28)
- FRED NASDAQCOM (7/29 종가 24,442.94, 8/28 26,402.42) — https://fred.stlouisfed.org/series/NASDAQCOM
- FOMC 성명 2026-07-29 (동결 9-3, 인상 반대 3인) — https://www.federalreserve.gov/newsevents/pressreleases/monetary20260729a.htm
- Warsh 잭슨홀 연설 2026-08-28 — https://www.federalreserve.gov/newsevents/speech/warsh20260828a.htm
- CNBC 9월 FOMC 인상 확률 (2026-08-28) — https://www.cnbc.com/2026/08/28/-september-fed-decision-now-a-coin-flip-as-rate-hike-odds-increase.html
- Forbes / Bill Stone 58% (2026-08-30) — https://www.forbes.com/sites/bill_stone/2026/08/30/fed-rate-hike-odds-rise-after-warshs-jackson-hole-speech/
- FOMC 일정 (9/15-16, 10/27-28 — 윈도우 내 2회) — https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm
- BLS 고용상황 2026년 7월 (NFP −23,000) — https://www.bls.gov/news.release/empsit.nr0.htm
- CNBC 근원 PCE 3.3% (2026-08-26) — https://www.cnbc.com/2026/08/26/feds-preferred-inflation-gauge-shows-core-prices-rose-3point3percent-annually-in-july.html
- CNBC Bessent 재무부 장기물 바이백 확대 (2026-08-19) — https://www.cnbc.com/2026/08/19/bessent-treasury-buybacks-yields-warsh-fed.html
- 시카고연준 NFCI −0.566 — https://www.chicagofed.org/research/data/nfci/current-data
- Morgan Stanley 2026 미드텀 선거 (11/03) — https://www.morganstanley.com/insights/articles/2026-us-midterm-elections-stock-market-impact
- Motley Fool 나스닥 2026년 두 번째 조정 진입 (2026-07-31) — https://www.fool.com/investing/2026/07/31/the-nasdaq-just-entered-second-correction-of-2026/
- 저장소 내부: `data/base_rates/volatility.md` (무조건부 44%, VIX<16 조건부 22%, 25+ 돌파 에피소드 목록)
- 저장소 내부: `data/base_rates/ml_auto.md` (VIX 앙상블 27%, 모델 불일치), `forecasts/2026/2026-07-15_vix-25-90d_r2.md` (직전 42%)
- 조건부 기저율 산출(8월말 앵커, VIX<16, 직전 12개월 돌파 이력 33.3% 등): FRED VIXCLS 1990~2026 전체 이력(n=9,261) 직접 집계, CBOE 원본과 최대 오차 0.0000 교차검증, 재현 가능

**[미검증]** 표기: VIX/VIX3M 0.826(2026-08-27)은 2차 출처. CTA −3%/−5% 트리거 규모는 2차 출처 경유로 원문 미확보. 1993년 이전 VIX는 현행 방법론으로 소급 산출된 값이며 실거래 기반이 아니다.
