---
forecast_id: 2026-07-15_fomc-2026-07-29-hike_r2
question_id: fomc-2026-07-29-hike
question_snapshot: 2026-07-29 종료되는 FOMC 회의에서 연준이 연방기금금리 목표범위를 25bp 이상 인상할 확률은?
timestamp: 2026-07-15 10:08 KST
phase: P1
model: claude-opus-4-8
prompt_version: reasoning_core_v1
probability: 3
ci80: [1, 7]
window_end: null
snapshots: {}
market_implied: null
edge: null
sources_count: 151
method: p1-pipeline/2agents
cost_usd: 1.0958
ensemble_runs: [3]
divergence: null
---

## [0] 질문 검증
판정 기준 명확: 2026-07-29 FOMC 성명서상 목표범위 상단이 직전 3.50~3.75% 대비 +25bp 이상(상단 4.00% 이상)이면 YES. 기계적 판정으로 모호성 낮음. 불확실성은 오직 '연준이 인상하는가'에 집중.

## [1] Outside View — base rate (anchor: 3%)
참조 클래스: 완화(인하)·동결 국면 진행 중 예정된 단일 FOMC 회의에서 즉시 인상(방향 급선회)이 발생한 사례

- 완화/동결 국면 도중 다음 예정회의에서 곧바로 25bp+ 인상 전환: 근대(1990년대 이후) 극소수, 정량치 NOT FOUND (general 보고, 미검증)
- 단일 예정회의의 기본 행동은 '동결'이 지배적이며 방향 전환은 예외적 (general 보고, 미검증)
- 연준은 통상 수개월 전 시그널링(연설·점도표·의사록) 후 실행하며 무예고 인상 급선회는 이례적 (devil 보고, 미검증)

## [2] Inside View — 보정
| 증거 | 방향 | 조정 |
|---|---|---|
| 현행 3.50~3.75%는 고점(5.25~5.50%) 대비 낮아 인하 사이클 진행 중을 시사 → 같은 회의 인상 급선회는 관행상 극히 이례적 (general 보고) | ↓ | −1%p |
| YES 기준이 '+25bp 이상'으로 50bp 상방 서프라이즈까지 포함 → 인플레 쇼크 시 꼬리위험 존재 (devil 보고) | ↑ | +1%p |
| 인플레 재점화·관세·에너지 쇼크 등 상방 트리거 신호의 실제 존재 여부는 모두 NOT FOUND → 긴급 재긴축 명분 부재 | ↓ | −1%p |

## [3] 분해 트리
YES 성립 = (인플레/충격 트리거 발생) AND (연준이 9월 지연이 아닌 7월 즉시 실행) AND (대응이 매파 문구가 아닌 실제 25bp+ 인상). 각 조건 확률 낮음(트리거 ~15%, 즉시실행 조건부 ~15%, 문구 아닌 실행 ~50%) → 곱하면 약 1% 수준. 이는 anchor 2~3%와 대체로 일치하며 꼬리위험 여유로 3% 부근 채택.

## [4] Premortem — 이 예측이 크게 틀렸다면
1. 7월 직전 6월 CPI/PCE가 예상 크게 상회하여 기대인플레 이탈 → 연준 선제 방어 인상 (검증 실패, 지표 NOT FOUND)
2. 관세 전가·에너지/지정학 쇼크로 헤드라인·근원 동반 급등 → 긴급 재긴축
3. 달러·채권 불안(재정적자發 장기금리 급등)으로 통화방어성 인상, 그러나 대개 9월 지연·매파 문구로 귀결되어 7월 시간제약이 강한 허들

## [5] 최종 출력
- **최종 확률: 3%** (80% CI: 1~7%)
- **핵심 근거**:
  1. 인하/동결 국면 중 다음 예정회의 즉시 25bp+ 인상 급선회는 연준 관행상 극히 이례적 (미검증 base rate)
  2. 연준은 사전 시그널 없이 급선회하지 않으며, 인플레 쇼크 시에도 통상 '동결+매파 문구'로 대응하고 실제 인상은 뒤로 미룸
  3. 현재 인플레 재점화·긴급 재긴축 트리거 신호의 존재 근거가 모두 NOT FOUND
- **관찰 지표**:
  1. CME FedWatch 2026-07-29 회의 인상 확률 분포
  2. 6월 CPI/PCE 서프라이즈 폭 및 연준 인사 매파 발언·사전 시그널 유무

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전).

## [미검증] 항목
- 웹서치 도구 장애로 CME FedWatch 확률·컨센서스·현 정책금리 공식확인·직전 성명서 톤·최근 CPI/PCE/고용 실측치 모두 회수 실패
- 현행 목표범위 3.50~3.75%는 질문 전제로만 제시, 독립적 공식 확인 NOT FOUND
- 제시된 base rate(인하국면 중 즉시 재인상 빈도)는 일반지식 기반 미검증치로 확정 근거 아님
- 7월 회의 SEP(점도표) 발표 여부 미확인

## 리서치 구성
general(출처 76), devil(출처 75) — 증거 부록: `2026-07-15_fomc-2026-07-29-hike_r2_evidence.md`
