---
forecast_id: 2026-08-08_adbe-eps-beat-fq3-2026_r1
question_id: adbe-eps-beat-fq3-2026
question_snapshot: Adobe가 2026-09-10(장후 추정) 발표하는 FQ3 2026 실적에서 조정 EPS가 발표 직전 컨센서스를 상회할 확률은?
timestamp: 2026-08-08 12:46 KST
phase: P1
model: gpt-5.6-terra
provider: openai
model_snapshot: gpt-5.6-terra
provider_version: reasoning_core_v1
prompt_version: reasoning_core_v1
probability: 59
ci80: [40, 76]
window_end: null
snapshots: {}
market_implied: null
edge: null
research_status: failed
sources_count: 0
method: p1-pipeline/2agents
cost_usd: 0.21
ensemble_runs: [59]
divergence: null
shadow_extremized: 65
digest_hash: null
digest_inputs: null
pipeline_tier: lite
ml_divergence_pp: null
divergence_note: null
divergence_class: null
research_quality:
  sources: {t1: 2, t2: 0, t3: 2, t4: 0, unknown: 3}
  n_urls: 7
  primary_ratio: 0.286
---

## [0] 질문 검증
해소 가능하다. YES는 Adobe IR의 FQ3 FY2026 non-GAAP diluted EPS가 2026-09-07(D-3) 최종 컨센서스를 ‘엄격히’ 초과하는 경우이며, 동률은 NO다. 단, 2026-09-10 장후 발표일은 공식 확정이 아닌 과거 일정 기반 추정이므로 실제 Adobe IR 발표 및 D-3 컨센서스 스냅샷으로 판정해야 한다. [source: MarketBeat, 2026-08-08; Adobe IR, 2026-06-11]

## [1] Outside View — base rate (anchor: 67%)
참조 클래스: Adobe의 분기 non-GAAP diluted EPS가 발표 직전 시장 컨센서스를 엄격히 상회하는 사건. 특히 회사가 제시한 EPS 가이던스 범위와 컨센서스가 근접하고, 동률도 실패로 처리되는 대형 소프트웨어 기업의 분기 실적 사례다.

- 최근 3개 Adobe 분기에서 제시된 EPS-컨센서스 비교는 모두 상회였다: FQ2 FY26 $5.96 vs $5.82, FQ1 FY26 $6.06 vs $5.87, FQ4 FY25 $5.50 vs $5.40. 표본 기준 3/3=100%이나 표본이 매우 작고 단일 비공식 집계이므로 그대로 사용하지 않았다. [source: Drillr, 2026-08-05]
- 동일 데이터 제공자는 Adobe가 최근 12/12분기 EPS를 상회했고 최근 4개 분기 평균 서프라이즈가 +2.5%라고 제시한다. 단일 비공식 제공자 집계라서 독립적 확률 근거가 아니라 상향 역사성의 보조 근거로만 반영했다. [source: Drillr, 2026-08-05]
- Adobe 공식자료로 확인되는 최근 실제 non-GAAP EPS는 FQ1 FY26 $6.06 및 FQ2 FY26 $5.96이다. 이는 최근 실적 수준은 확인하지만, 공식 컨센서스 비교 자료는 아니다. [source: Adobe IR, 2026-06-11]

## [2] Inside View — 보정
| 증거 | 방향 | 조정 |
|---|---|---|
| FQ3 회사 non-GAAP EPS 가이던스는 $6.05–$6.10이며, 현재 공개 제3자 추정치 $6.08과 중앙값($6.075)이 사실상 같거나 소폭 낮다. 가이던스 수준 달성만으로는 엄격한 컨센서스 상회를 보장하지 않는다. [source: Adobe IR, 2026-06-11; Drillr, 2026-08-05] | ↓ | −4%p |
| FQ3 non-GAAP 영업마진 가정은 약 44.0%로 FY26 가정 45.0%보다 낮고, FQ2의 44.5%도 FQ1의 47.4%보다 2.9%p 낮았다. EPS 상회 여력에 부정적이다. [source: Adobe IR, 2026-06-11] | ↓ | −5%p |
| Dan Durn CFO 퇴임 및 Steve Day interim CFO 체제는 실적 산출·비용집행·통합 과정의 불확실성을 높이는 사건이다. 이는 인과가 확정된 악재가 아니라 실행 리스크 보정이다. [source: Adobe SEC filing, 2026-06-11] | ↓ | −3%p |
| AI-first ARR은 전년 대비 3배 이상이며 $500m를 초과했고, Q2 구독매출은 전년 대비 14% 성장했다. 수요 및 반복매출 추세는 가이던스 상단 또는 소폭 상회 가능성을 지지한다. [source: Adobe IR, 2026-06-11] | ↑ | +4%p |

## [3] 분해 트리
엄격한 EPS 상회
├─ A. D-3 컨센서스가 현재 공개 추정치($6.07–$6.08) 부근에 머문다: 60% [예측 추정; 실제 D-3 값은 현재 NOT FOUND]
│  └─ B. Adobe가 그 문턱을 엄격히 넘는 non-GAAP EPS를 발표: 75% [예측 추정; 최근 상회 이력·AI/구독 성장과 낮은 FQ3 마진 가정을 함께 반영]
│     └─ A AND B = 45%
└─ C. D-3 컨센서스가 상향되어 $6.08을 넘는 쪽으로 이동한다: 40% [예측 추정]
   └─ D. 더 높은 문턱도 엄격히 초과: 35% [예측 추정; $6.10 상단 및 마진 압박이 제약]
      └─ C AND D = 14%
합계 약 59%. 이 결과는 anchor(67%)에 가이던스-컨센서스 근접성, 마진, CFO 전환을 반영한 inside-view 결과(59%)와 일치한다. 수치는 자료에 없는 미래 사건에 대한 예측 추정이며, 사실 수치가 아니다.

## [4] Premortem — 이 예측이 크게 틀렸다면
1. D-3 컨센서스가 $6.10 부근으로 상향되는데 Adobe EPS가 $6.07–$6.10에 머문다. 가이던스 충족 또는 동률도 NO인 비대칭 판정이 누락되면 확률을 과대평가하게 된다. [source: Adobe IR, 2026-06-11]
2. FQ3의 약 44.0% non-GAAP 영업마진 가정이 비용·통합 부담으로 달성되지 않아, 매출이 성장해도 EPS가 컨센서스를 넘지 못한다. FQ1→FQ2 FY26에 매출은 증가했지만 non-GAAP EPS는 $6.06에서 $5.96으로 하락한 선례가 있다. [source: Adobe IR, 2026-06-11]
3. Semrush 편입 뒤 통합·비용·매출인식 변동성이 예상보다 커진다. Adobe는 관련 goodwill impairment 및 법률 관련 loss contingencies를 기록했다고 공시했다; 비GAAP 조정 여부와 별개로 운영상 변동성 위험이다. [source: Adobe SEC filing, 2026-06-15]

## [5] 최종 출력
- **최종 확률: 59%** (80% CI: 40~76%)
- **핵심 근거**:
  1. 최근 제시된 Adobe EPS-컨센서스 비교는 3개 연속 상회이고, 비공식 집계상 최근 12개 분기도 모두 상회다. 다만 단일 비공식 데이터의 작은/선택 편향 가능성을 감안해 anchor를 67%로 보수적으로 낮췄다. [source: Drillr, 2026-08-05]
  2. FQ3 공식 EPS 가이던스 $6.05–$6.10의 중앙값은 현 공개 추정치 $6.08보다 $0.005 낮다. 따라서 ‘가이던스 내 실적’이 아니라 실제 초과 실행이 필요하다. [source: Adobe IR, 2026-06-11; Drillr, 2026-08-05]
  3. AI-first ARR 3배 이상·$500m 초과 및 Q2 구독매출 14% 성장은 상방 요인이나, FQ3 44.0% 마진 가정과 CFO 전환은 EPS 초과의 여유를 제한한다. [source: Adobe IR, 2026-06-11; Adobe SEC filing, 2026-06-11]
- **관찰 지표**:
  1. 2026-09-07에 확보할 최종 컨센서스 EPS: $6.08 이하로 유지되면 YES 확률이 상승하고, $6.10 부근 이상으로 상향되면 하락한다. 현재 판정용 값은 NOT FOUND다.
  2. 발표 전 Adobe의 공식 사업 업데이트에서 Digital Media/구독 성장과 FQ3 non-GAAP 영업마진 약 44.0% 가정의 유지·악화 여부: 마진 압박 완화는 상승, 추가 비용·통합 문제는 하락 신호다. [source: Adobe IR, 2026-06-11]

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전).

## [미검증] 항목
- D-3(2026-09-07) 최종 컨센서스 EPS는 미래 스냅샷이므로 NOT FOUND이며, 현재 공개된 $6.08 또는 TipRanks의 $6.07을 판정값으로 대체하지 않았다. [source: Drillr, 2026-08-05; TipRanks, 2026-08-초 접근]
- 2026-09-10 장후 발표 일정은 Adobe 공식 확정 일정이 아니라 과거 패턴 기반 추정이다. [source: MarketBeat, 2026-08-08]
- 매크로·옵션 포지셔닝·주가 및 컨센서스 수정 추이의 최신 정량 자료는 제공 패키지에서 확인되지 않아 확률 조정에 사용하지 않았다.

## 리서치 구성
general(출처 0), devil(출처 0) — 증거 부록: `2026-08-08_adbe-eps-beat-fq3-2026_r1_evidence.md`
