---
forecast_id: 2026-08-31_orcl-eps-beat-fq1-2027_r1
question_id: orcl-eps-beat-fq1-2027
question_snapshot: "Oracle이 2026년 9월 둘째 주(9/8~9/14 추정, 장후) 발표하는 FQ1 2027 실적에서 조정 EPS가 발표 직전 컨센서스를 상회할 확률은?"
timestamp: 2026-08-31 16:20 KST
phase: P1
model: claude-opus-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 63
ci80: [48, 76]
window_end: null
snapshots:
  consensus_adjusted_eps: "$1.74 (Yahoo Finance / LSEG, n=33, 범위 $1.64~1.81, 채취 2026-08-31 KST) — 판정 기준. TipRanks $1.74·Investing.com $1.73 교차 일치"
  consensus_outlier_note: "MarketBeat $1.53은 애널리스트 최저치($1.64)와 회사 가이던스 하단($1.72)을 모두 하회하는 이상치 — 미사용. AlphaQuery $1.40은 GAAP 계열로 비교 불가"
  consensus_revenue: "$19.13B (Investing.com)"
  company_guidance: "non-GAAP EPS $1.72~$1.76, 매출 성장 +27~29%, 클라우드 +57~63% cc (2026-06-10 FQ4 콜) — 컨센서스가 가이던스 중앙값에 정확히 위치"
  report_date: "미확정. Oracle 'Sets the Date' 공지 2026-08-31 현재 미발행(전년: 2025-09-02 발행 → 09-09 발표). 제공사 추정 09-04~09-14, TipRanks·Investing.com은 09-14"
market_implied: null
edge: null
sources_count: 12
---

## [0] 질문 검증

판정 가능하나 **발표일이 미확정**이다. Oracle의 공식 Sets the Date 보도자료가 2026-08-31 현재 발행되지 않았고 제공사 추정이 09-04~09-14로 10일 폭에 흩어져 있다. 회사 관행상 발표 약 1주 전 공지하므로 9월 초 확정될 것으로 본다. 질문이 "실제 발표일에 판정"이라고 명시하므로 이 불확실성은 판정을 막지 않는다.

컨센서스는 **$1.74**로 고정한다 — Yahoo(n=33)·TipRanks가 $1.74, Investing.com이 $1.73으로 수렴하고, 무엇보다 **회사 가이던스 $1.72~$1.76의 정확한 중앙값**이다. MarketBeat $1.53은 애널리스트 최저치와 가이던스 하단을 모두 밑도는 이상치라 채택하지 않는다.

## [1] Outside View — base rate (anchor: 78%)

S&P 500 EPS 컨센서스 상회율(FactSet Earnings Insight 2026-08-28): **5년 평균 78% · 10년 평균 76% · Q2 2026 86%**(2021년 이후 최고). FactSet은 동률(tie)을 3%로 **별도 집계**하므로 이 수치는 이미 strict inequality 기준이며, 동률=NO인 본 질문에 그대로 쓸 수 있다.

두 가지 주의를 [2]에 반영한다. (1) Q3 2026 부정 가이던스 비율이 **36%**로 5년 평균 58%를 크게 밑돈다 — 워크다운이 약해 **다음 분기 허들이 높아졌다**. (2) 총계 서프라이즈 +26.5%는 Alphabet(지분증권 미실현이익 $98B)·Amazon($53.4B) 회계 아티팩트이며 제외 시 +10.8%, Mag 7은 +66.2%에서 **+4.4%**로 떨어진다. 서프라이즈 폭을 헤드라인 수치로 잡으면 안 된다.

ORCL 고유 이력: 8분기 중 **5비트 / 3미스**. 미스는 전부 근소(−0.6% · −1.3% · −0.7%).

## [2] Inside View — 보정 (항목별)

| 증거 | 방향 | 조정 |
|---|---|---|
| **메가캡 중 비트율이 가장 낮다** — 8분기 5/8 | 하락 | −12%p |
| **직전년 동일 회계분기(FQ1 2026, 2025-09-09)가 $1.47 vs $1.48로 1센트 미스** — 본 질문과 같은 분기에서의 미스 전례 | 하락 | −5%p |
| 컨센서스가 가이던스 중앙값에 딱 붙음 — 가이던스 상단($1.76) 달성해야 +1.1% 서프라이즈 | 하락 | −4%p |
| 매출은 상습적으로 컨센서스 하회(최근 4분기 평균 −1.9%) — EPS 비트가 마진·자사주에 의존 | 하락 | −2%p |
| **EPS를 명시적으로 가이드하는 유일한 종목** — 범위 제시는 경영진이 방어 가능하다고 본다는 신호 | 상승 | +3%p |
| 클라우드 수요 강세 — FQ4 매출 $19.2B(+21%), FY2027 매출 $90B 유지, non-GAAP EPS 전망 $8.05로 상향 | 상승 | +3%p |
| 최근 2분기 연속 비트(+5.7%, +7.5%)로 직전 미스 구간에서 회복 | 상승 | +2%p |

순 조정 **−15%p** → 63%.

## [3] 분해 트리

| 경로 | 확률 | 비트 조건부 | 기여 |
|---|---|---|---|
| 클라우드 성장 가이던스(+57~63% cc) 달성·초과 | 0.65 | 0.80 | 52% |
| 클라우드 부합하나 capex(약 $55.7B) 감가상각이 마진 잠식 | 0.25 | 0.35 | 9% |
| 클라우드 미달 | 0.10 | 0.15 | 2% |
| 합계 | | | **63%** |

anchor 78%에서 15%p를 깎은 근거는 **종목 고유 실적**이다. 8분기 5/8은 S&P 평균보다 크게 낮고, 직전년 동일 분기 1센트 미스는 우연으로 보기 어렵다.

## [4] Premortem — 틀릴 이유 3가지

1. **8분기 표본이 너무 작은 경우.** 5/8과 78%의 차이는 이항 표준오차(약 15%p) 안에 들어간다. 종목 고유 신호로 15%p를 깎은 것이 과적합이면 실제값은 72~75%다.
2. **AI 인프라 수요가 마진을 밀어올리는 경우.** OCI 백로그와 FY2027 EPS 상향($8.05)은 경영진의 자신감을 보여준다. 클라우드 매출 믹스 개선이 마진을 끌어올리면 가이던스 상단을 넘길 수 있다.
3. **반대 방향 — 63%도 높은 경우.** 컨센서스가 가이던스 중앙값이라는 것은 애널리스트가 회사 숫자를 그대로 옮겼다는 뜻이다. 실적이 범위 중앙에 착지하면 **동률에 가까운 미스**가 되고, 동률=NO는 직접적 하방이다.

## [5] 최종 출력

- 최종 확률: **63%** (80% CI: 48~76%)
- **핵심 근거 3줄**:
  1. Oracle은 8분기 5/8 비트로 메가캡 중 기록이 가장 나쁘고 미스는 전부 1~2센트 근소차였다.
  2. 직전년 동일 회계분기(FQ1 2026)에서 $1.47 vs $1.48로 1센트 미스한 전례가 있다.
  3. 컨센서스 $1.74가 회사 가이던스 $1.72~$1.76의 정확한 중앙값이라 상방 여지가 구조적으로 좁다.
- **관찰 지표 2개**:
  1. **Sets the Date 공지와 D-1 컨센서스** — $1.76(가이던스 상단) 이상이면 55%로 하향.
  2. **FQ1 클라우드 매출 성장률** — 가이던스 상단 초과 시 EPS 비트 확률이 크게 오른다.

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전).

## 출처 목록

- Oracle FQ4 FY2026 실적 (non-GAAP EPS $2.111, FQ1 가이던스 $1.72~1.76) — https://investor.oracle.com/investor-news/news-details/2026/Oracle-Announces-Record-Q4-and-FY-2026-Results-Driven-by-Cloud-Infrastructure--Cloud-Applications/default.aspx (2026-06-10)
- 전년 Sets the Date 사례 — https://investor.oracle.com/investor-news/news-details/2025/Oracle-Sets-the-Date-for-its-First-Quarter-Fiscal-Year-2026-Earnings-Announcement/default.aspx
- Oracle FQ1 FY2026 실적 (2025-09-09, EPS $1.47 vs 컨센 $1.48 — 1센트 미스) — https://www.cnbc.com/2025/09/09/oracle-orcl-q1-earnings-report-2026.html
- Yahoo Finance / LSEG ORCL 컨센서스 ($1.74, n=33) — https://finance.yahoo.com/quote/ORCL/analysis/ (채취 2026-08-31)
- TipRanks ORCL 실적 — https://www.tipranks.com/stocks/orcl/earnings
- Investing.com ORCL 실적 — https://www.investing.com/equities/oracle-corp-earnings
- S&P Oracle 신용등급 BBB− 하향 (2026-07-09) — https://insight.factset.com/hyperscalers-tap-external-financing-as-ai-capex-outruns-cash-flow
- FactSet Earnings Insight 2026-08-28 (비트율 86%/78%/76%, 동률 3%, Q3 부정 가이던스 36%, Mag7 서프라이즈 ex-2종목 +4.4%) — https://advantage.factset.com/hubfs/Website/Resources%20Section/Research%20Desk/Earnings%20Insight/EarningsInsight_082826.pdf
- Warsh 잭슨홀 연설 2026-08-28 (9월 인상 확률 약 56~58%) — https://www.federalreserve.gov/newsevents/speech/warsh20260828a.htm
- NVIDIA FQ2 2027 실적 (AI 수요 교차확인) — https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-second-quarter-fiscal-2027 (2026-08-26)

**[미검증]** 표기: 발표일은 회사 미확정이며 제공사 추정이 09-04~09-14로 흩어져 있다. 최근 4분기 매출 서프라이즈 평균 −1.9%는 2차 집계 경유. FY26 Q2의 +38.0% 서프라이즈는 이상치로 판단해 기저율에서 별도 취급했다.
