---
forecast_id: 2026-08-31_avgo-eps-beat-fq3-2026_r1
question_id: avgo-eps-beat-fq3-2026
question_snapshot: "Broadcom이 2026-09-03(장후 예상) 발표하는 FQ3 2026 실적에서 조정 EPS가 발표 직전 컨센서스를 상회할 확률은?"
timestamp: 2026-08-31 16:10 KST
phase: P1
model: claude-opus-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 82
ci80: [70, 90]
window_end: null
snapshots:
  consensus_adjusted_eps: "$3.238 (Yahoo Finance / LSEG 집계, n=38, 범위 $3.08~3.33, 채취 2026-08-31 KST) — 판정 기준"
  consensus_vendor_note: "Zacks/Nasdaq 계열 $2.83은 다른 조정 기준(같은 소스가 FQ2 actual을 $2.17로 기록하나 회사 보고 non-GAAP은 $2.44). 판정은 회사 non-GAAP 정의와 정합한 LSEG 기준으로 고정"
  consensus_revenue: "$29.435B (Yahoo/LSEG, n=37)"
  company_guidance: "매출 약 $29.4B(+84% YoY), non-GAAP 영업이익률 약 67%, AI 반도체 $16.0B(+200%↑). EPS 가이던스 미제시 (2026-06-03 8-K)"
  report_date: "2026-09-02 (수) 미국 장마감 후 ET = KST 09-03 새벽 — Broadcom IR 확정 공지"
market_implied: null
edge: null
sources_count: 14
---

## [0] 질문 검증

판정 가능하나 **벤더 고정이 필수**다. 조정 EPS 컨센서스가 제공사별로 $3.238(LSEG)과 $2.83(Zacks 계열)으로 갈리는데, 두 값은 같은 분기에 대한 이견이 아니라 **조정 정의 자체가 다르다**. 같은 Zacks 소스가 FQ2 FY26 actual을 $2.17로 기록하는 반면 Broadcom이 8-K에 보고한 non-GAAP diluted EPS는 $2.44다. 발표 당일 beat/miss 헤드라인에 쓰이는 숫자는 회사 non-GAAP 정의와 정합한 **LSEG 기준 $3.238**이므로 이를 판정 스냅샷으로 고정한다.

발표일은 Broadcom IR이 확정 공지한 **2026-09-02 장마감 후 ET**(KST 09-03 새벽)로, 질문의 마감 2026-09-03과 정합한다.

## [1] Outside View — base rate (anchor: 78%)

S&P 500 EPS 컨센서스 상회율(FactSet Earnings Insight 2026-08-28): **5년 평균 78% · 10년 평균 76% · Q2 2026 86%**(2021년 이후 최고). FactSet은 동률(tie)을 3%로 **별도 집계**하므로 이 수치는 이미 strict inequality 기준이며, 동률=NO인 본 질문에 그대로 쓸 수 있다.

주의 두 가지를 [2]에 반영한다. (1) Q3 2026 부정 가이던스 비율이 **36%**로 5년 평균 58%를 크게 밑돈다 — 워크다운이 약해 **다음 분기 허들이 높아졌다**. (2) 총계 서프라이즈 +26.5%는 Alphabet(지분증권 미실현이익 $98B)·Amazon($53.4B) 회계 아티팩트이며 제외 시 +10.8%, Mag 7은 +66.2%에서 **+4.4%**로 떨어진다. 서프라이즈 폭을 헤드라인 수치로 잡으면 안 된다.

AVGO 고유 이력(LSEG·8-K 대조 검증): **7분기 연속 비트**, 서프라이즈 중앙값 **+1.74%**, 최근 4분기 +1.32% / +1.60% / +4.38% / +1.74%.

## [2] Inside View — 보정 (항목별)

| 증거 | 방향 | 조정 |
|---|---|---|
| 7분기 연속 비트 — FQ4 FY24부터 FQ2 FY26까지 무패 | 상승 | +6%p |
| AI 반도체 수요 검증 — FQ3 가이던스 AI 반도체 $16.0B(+200% YoY). NVDA FQ2(08-26) 블로우아웃으로 AI 수요 서사 재확인 | 상승 | +2%p |
| 하이퍼스케일러 capex 전원 유지·상향(GOOGL $195~205B, AMZN 약 $220B) — AVGO 커스텀 ASIC 수요의 직접 선행지표 | 상승 | +2%p |
| **서프라이즈 폭이 매우 좁다** — 중앙값 +1.74%. 동률=NO 규칙에서 메가캡 중 tie·근소미스 리스크가 가장 큰 종목 | 하락 | −5%p |
| 워크다운 약화 — Q3 2026 부정 가이던스 36%(5년 58%). 허들이 평소보다 높음 | 하락 | −2%p |
| 회사가 EPS를 가이드하지 않음 — 매출·마진율만 제시해 컨센서스 수렴도가 EPS 가이드 종목보다 낮음 | 하락 | −1%p |
| 메모리 원가 상승의 마진 전가 국면(NVDA 총이익률 75.0%→74.0% 가이던스) — AVGO도 무관하지 않음 | 하락 | −2%p |

순 조정 **0%p** → 82%. (anchor 78%에 종목 고유 연속비트 프리미엄 +4%p)

## [3] 분해 트리

| 경로 | 확률 | 비트 조건부 | 기여 |
|---|---|---|---|
| AI 반도체 $16.0B 가이던스 달성·초과 | 0.80 | 0.93 | 74% |
| AI는 부합하나 비AI(인프라 소프트웨어·무선) 부진 | 0.15 | 0.50 | 8% |
| AI 출하 지연·공급 제약 | 0.05 | 0.10 | 1% |
| 합계 | | | **83%** ≈ 82% |

이 종목의 핵심 리스크는 방향이 아니라 **폭**이다 — 중앙값 +1.74%는 컨센서스가 1.7%만 높게 잡혀도 미스가 된다는 뜻이다.

## [4] Premortem — 틀릴 이유 3가지

1. **컨센서스가 이미 가이던스를 완전히 반영한 경우.** 회사 매출 가이던스 $29.4B와 컨센서스 매출 $29.435B가 사실상 동일하다. 애널리스트가 가이던스에 딱 붙어 있으면 상방 여지가 마진에만 남는데, 메모리 원가 상승 국면에서 그 여지가 얇다.
2. **동률 또는 1센트 미스.** $3.238 컨센에 대해 중앙값 서프라이즈 +1.74%는 약 $0.056다. 회계 항목 하나로 뒤집히는 폭이며 동률은 NO로 판정된다.
3. **반대 방향 — 82%가 낮은 경우.** 7분기 무패에 AI 사이클이 정점 근처이고, 부정 가이던스 비율이 낮다는 것은 기업들이 자신 있다는 신호이기도 하다. FactSet Q2 2026 실측 비트율은 86%였다.

## [5] 최종 출력

- 최종 확률: **82%** (80% CI: 70~90%)
- **핵심 근거 3줄**:
  1. FactSet 5년 기저율 78%에 7분기 연속 비트 기록이 얹혀 상방이다.
  2. 다만 서프라이즈 중앙값이 +1.74%로 매우 좁아, 동률=NO 규칙에서 메가캡 중 가장 취약하다.
  3. AI 반도체 $16.0B 가이던스 달성 여부가 사실상 단일 분기점이며 NVDA FQ2 결과가 그 방향을 지지한다.
- **관찰 지표 2개**:
  1. **발표 D-1 컨센서스 재채취** — LSEG 기준이 $3.30 이상으로 올라가면 허들 상승으로 75%까지 하향.
  2. **9/2 발표의 AI 반도체 매출 라인** — $16.0B 미달 시 EPS 동반 미스 가능성이 높다.

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전).

## 출처 목록

- Broadcom IR 실적 발표 공지 (2026-09-02 장후 확정) — https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announce-third-quarter-fiscal-year-2026-financial
- Broadcom FQ2 FY2026 8-K EX-99.1 (non-GAAP EPS $2.44, FQ3 가이던스) — https://www.sec.gov/Archives/edgar/data/0001730168/000173016826000051/avgo-05032026x8kxex99.htm
- Yahoo Finance / LSEG AVGO 컨센서스 ($3.238, n=38) — https://finance.yahoo.com/quote/AVGO/analysis/ (채취 2026-08-31)
- Nasdaq(Zacks) AVGO 예측 ($2.83, n=8 — 다른 조정 기준) — https://www.nasdaq.com/market-activity/stocks/avgo/earnings
- FactSet Earnings Insight 2026-08-28 (비트율 86%/78%/76%, 동률 3%, Q3 부정 가이던스 36%, Mag7 서프라이즈 ex-2종목 +4.4%) — https://advantage.factset.com/hubfs/Website/Resources%20Section/Research%20Desk/Earnings%20Insight/EarningsInsight_082826.pdf
- NVIDIA FQ2 2027 실적 (AI 수요 교차확인, 총이익률 가이던스 74%) — https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-second-quarter-fiscal-2027 (2026-08-26)
- Alphabet Q2 2026 capex $195~205B 상향 — https://s206.q4cdn.com/479360582/files/doc_financials/2026/q2/2026q2-alphabet-earnings-release.pdf
- Microsoft FY26 Q4 (capex 회계 재분류) — https://www.microsoft.com/en-us/investor/earnings/fy-2026-q4/press-release-webcast

**[미검증]** 표기: 최근 4분기 평균 서프라이즈 +0.5%라는 2차 집계(24/7 Wall St 경유)는 본 회차가 확인한 LSEG 기준 수치(+1.32~+4.38%)와 불일치해 채택하지 않았다. 서프라이즈 이력 중 FQ4 FY24~FQ2 FY25 3개 분기 컨센서스는 TipRanks 경유로 **[부분 미검증]**이며, FQ3 FY25 이후 4개 분기는 Yahoo/LSEG와 CNBC 인용치가 일치해 검증됨.
