---
forecast_id: 2026-08-31_adbe-eps-beat-fq3-2026_r2
question_id: adbe-eps-beat-fq3-2026
question_snapshot: "Adobe가 2026-09-10(장후 추정) 발표하는 FQ3 2026 실적에서 조정 EPS가 발표 직전 컨센서스를 상회할 확률은?"
timestamp: 2026-08-31 20:00 KST
phase: P1
model: claude-opus-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 82
ci80: [69, 91]
window_end: null
snapshots:
  consensus_adjusted_eps: "$6.079 (Yahoo Finance / LSEG, n=29, 범위 $5.82~6.35, 채취 2026-08-31 KST) — 판정 기준, **회사 non-GAAP 정의 기준**. Zacks $6.08 · TipRanks $6.07(n=29) · Investing.com $6.07로 수렴"
  consensus_wrong_basis: "MarketBeat $4.84(n=3) · Nasdaq $4.86(n=12) · Barchart $4.86은 **GAAP도 non-GAAP도 아닌 제3기준**(주식보상만 제외). Adobe Q2 FY26 조정표로 확인: GAAP $4.25 → SBC 제외 $4.58 → 회사 non-GAAP $5.96. 이 기준으로 대조하면 8분기 전량 beat가 '4분기 중 2회 miss'로 뒤집힌다 — **사용 금지**"
  consensus_revenue: "$6.695B (Yahoo/LSEG, n=27) — 회사 가이던스 $6.67~6.72B 안"
  company_guidance: "FQ3 총매출 $6.67~6.72B, **GAAP EPS $4.40~4.45, non-GAAP EPS $6.05~6.10**, non-GAAP 영업이익률 약 44.0%, 희석주식수 약 395M (2026-06-11 SEC EX-99.1)"
  report_date: "**회사 미확정**. Adobe 뉴스룸·SEC에 FQ3 실적일 공지 부재(2026-07-17 이후 8-K 없음). 전례상 약 10일 전 공지(Q2는 06-01 공지 → 06-11 발표)"
market_implied: null
edge: null
sources_count: 12
---

## [0] 질문 검증

판정 가능하나 **기준 고정이 이 질문의 전부다.**

Adobe에 대해 **세 가지 기준이 동시에 유통**되고 있다. Q2 FY26 조정표(SEC EX-99.1, 2026-06-11)로 메커니즘을 특정했다 — GAAP $4.25 → 주식보상·이연보상 +$1.38 등 조정 → 회사 non-GAAP **$5.96**. 그런데 Nasdaq·Barchart·MarketBeat 클러스터가 쓰는 "EPS*"는 **$4.58**로, 무형자산상각·소송충당 등만 가산하고 **주식보상은 가산하지 않은 제3의 기준**이다.

결과가 정반대로 갈린다:

| 기준 | 최근 이력 |
|---|---|
| 회사 non-GAAP (LSEG·Yahoo·TipRanks·Investing.com) | **8분기 전량 beat** (+1.8~+3.4%) |
| Nasdaq/Barchart "EPS*" | **4분기 중 2회 miss** (2026-05 −3.4%, 2026-02 −0.4%) |

질문이 "**조정 EPS**"를 묻고 Adobe가 그 값을 직접 공표하므로, 판정 기준은 **회사 non-GAAP 정의와 정합한 $6.079(Yahoo/LSEG)**로 고정한다. $4.84~4.86 클러스터는 사용하지 않는다.

제3기준에서 miss가 나는 이유도 구조적으로 설명된다 — 가이던스를 그 기준으로 환산하면 약 $4.58~4.63인데 컨센서스가 $4.86이라 **가이던스 상단보다 $0.23 높다**. 그 기준에서는 miss가 사실상 예정돼 있다.

발표일은 회사 미확정이다(2026-07-17 이후 8-K 부재). 전례상 약 10일 전 공지이므로 곧 확정될 것으로 본다.

r1(2026-08-08)은 `snapshots: {}`였다. 이번 회차에서 벤더·기준·값을 고정한다.

## [1] Outside View — base rate (anchor: 78%)

S&P 500 EPS 컨센서스 상회율(FactSet Earnings Insight 2026-08-28): **5년 78% · 10년 76% · Q2 2026 86%**. 동률(tie)은 3%로 별도 집계되므로 strict-inequality(동률=NO) 질문에 그대로 쓸 수 있다. 단 Q3 2026 부정 가이던스 비율이 36%로 5년 평균 58%를 크게 밑돌아 **워크다운이 약하고 허들이 높다**.

ADBE 고유 이력(회사 non-GAAP, SEC 원문 대조): **8분기 전량 beat**, 서프라이즈 +1.8% ~ +3.4%, 중앙값 약 +2.5%. **매우 좁고 안정적인 분포**다.

## [2] Inside View — 보정 (항목별)

| 증거 | 방향 | 조정 |
|---|---|---|
| **8분기 전량 beat**에 서프라이즈 분포가 +1.8~3.4%로 좁다 — 방향과 폭이 모두 일관 | 상승 | +6%p |
| 컨센서스 $6.079가 가이던스 $6.05~6.10 **중앙 바로 위**이고, Adobe는 8분기 연속 가이던스를 넘겼다. 중앙값 서프라이즈 +2.5%면 약 $6.10~6.15로 가이던스 상단 초과 | 상승 | +3%p |
| AI 수익화가 실적으로 확인 — AI-first ARR **$5억 초과·전년 3배**, Firefly ARR 약 $3억 근접(QoQ +약 50%), Acrobat AI Assistant 유료 MAU +150% YoY | 상승 | +2%p |
| **서프라이즈 폭이 좁다는 것은 양날** — 중앙값 +2.5%는 컨센서스가 2.5%만 높아도 miss라는 뜻. 다만 Adobe는 EPS를 명시적으로 가이드해 컨센서스가 그 범위에 수렴하므로 AVGO보다는 안전 | 하락 | −2%p |
| **freemium 전환에 따른 단기 ARR 역풍** — Creative Cloud 가격 인상을 유예하고 무료 사용자 확보를 우선. Q2는 beat했음에도 시간외 −1.24% | 하락 | −2%p |
| **CFO 공석** — Dan Durn 2026-06-15자 퇴사, Steve Day 임시 CFO. FQ3는 임시 CFO 체제의 첫 온전한 분기 | 하락 | −2%p |
| Morgan Stanley가 2단계 강등(Underweight, PT $365→$240, 2026-07-21) — "생성형 AI 파괴가 ARR 재가속 경로를 흐린다" | 하락 | −1%p |
| 워크다운 약화(부정 가이던스 36%) | 하락 | −1%p |
| 컨센서스가 **30일간 리비전 0건**으로 완전 정체 — 새 정보가 반영되지 않은 상태 | 하락 | −1%p |

순 조정 **+2%p** → 82%. (anchor 78% + 종목 프리미엄 +2%p + 순조정 +2%p)

## [3] 분해 트리

| 경로 | 확률 | 비트 조건부 | 기여 |
|---|---|---|---|
| 매출 가이던스 범위 내 + 영업이익률 약 44% 유지 | 0.70 | 0.93 | 65% |
| 매출 하단이나 마진·자사주로 상쇄 | 0.20 | 0.70 | 14% |
| freemium 전환이 ARR·매출을 가이던스 아래로 | 0.10 | 0.30 | 3% |
| 합계 | | | **82%** |

## [4] Premortem — 틀릴 이유 3가지

1. **freemium 전환 비용이 이번 분기에 집중되는 경우.** 가격 인상 유예와 무료 사용자 확보는 단기 매출을 직접 깎는다. 경영진이 2027년 LTV를 위해 의도적으로 감수하는 것이라, 그 비용이 FQ3에 몰리면 가이던스 하단도 위험하다.
2. **임시 CFO 체제의 보수적 마감.** CFO 교체기에는 충당금·비용 인식이 보수적으로 기울기 쉽다. 8분기 연속 beat 패턴이 이 한 분기에 끊길 수 있는 실제 경로다.
3. **반대 방향 — 82%가 낮은 경우.** 8분기 전량 beat에 서프라이즈가 +1.8~3.4%로 매우 안정적이고, 컨센서스가 가이던스 중앙이며 30일간 움직이지 않았다. 회사가 가이던스를 넘기기만 하면 beat다. 87~90%가 맞을 수 있다.

## [5] 최종 출력

- 최종 확률: **82%** (80% CI: 69~91%)
- 직전 대비: r1 59% → r2 82% (**+23%p**). r1은 `snapshots: {}`로 컨센서스를 기록하지 않았다. 이번 회차에서 (1) 판정 기준을 **회사 non-GAAP $6.079**로 고정하고, (2) 그 기준의 **8분기 전량 beat**와 좁은 서프라이즈 분포(+1.8~3.4%)를 확인했으며, (3) 컨센서스가 가이던스 $6.05~6.10 중앙에 있음을 확인해 상향했다.
- **가장 중요한 발견**: 널리 유통되는 $4.84~4.86 컨센서스는 **GAAP도 non-GAAP도 아닌 제3기준**이며, 이 기준으로 판정하면 같은 회사가 "8분기 전량 beat"에서 "4분기 중 2회 miss"로 뒤집힌다. 해소 시 반드시 회사 non-GAAP 기준으로 대조해야 한다.
- **핵심 근거 3줄**:
  1. 회사 non-GAAP 기준 8분기 전량 beat이며 서프라이즈가 +1.8~3.4%로 매우 안정적이다.
  2. 컨센서스 $6.079가 회사 가이던스 $6.05~6.10 중앙에 있어, 가이던스만 넘기면 beat가 된다.
  3. 하방은 freemium 전환의 단기 ARR 역풍과 임시 CFO 체제이며, 방향보다 폭을 줄이는 요인이다.
- **관찰 지표 2개**:
  1. **발표일 공지와 D-1 컨센서스 기준 재확인** — $6.20 이상으로 상향되면 허들 상승으로 72%까지 하향.
  2. **Creative Cloud freemium 전환 관련 ARR 코멘트** — 분기 중 ARR 가이던스 하향 시사가 나오면 −10%p 이상.

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전).

## 출처 목록

- Adobe Q2 FY2026 실적 8-K EX-99.1 (GAAP $4.25 / non-GAAP $5.96 조정표, FQ3 가이던스 GAAP $4.40~4.45 · non-GAAP $6.05~6.10, 매출 $6.67~6.72B, AI-first ARR $5억 초과) — https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000796343&type=8-K (2026-06-11)
- Yahoo Finance / LSEG ADBE 컨센서스 ($6.079, n=29, 범위 $5.82~6.35) — https://finance.yahoo.com/quote/ADBE/analysis/ (채취 2026-08-31)
- TipRanks ADBE 실적 (컨센 $6.07, n=29) — https://www.tipranks.com/stocks/adbe/earnings
- Investing.com ADBE 실적 (컨센 $6.07) — https://www.investing.com/equities/adobe-sys-inc-earnings
- Nasdaq ADBE 예측 ($4.86, n=12 — 제3기준, 4주간 리비전 0) — https://www.nasdaq.com/market-activity/stocks/adbe/earnings
- MarketBeat ADBE ($4.84, n=3 — 제3기준) — https://www.marketbeat.com/stocks/NASDAQ/ADBE/earnings/
- Adobe SEC 제출 목록 (2026-07-17 이후 8-K 부재 — 발표일 회사 미확정 확인) — https://data.sec.gov/submissions/CIK0000796343.json
- Morgan Stanley ADBE 2단계 강등 Underweight PT $365→$240 (2026-07-21) — 2차 출처 경유
- FactSet Earnings Insight 2026-08-28 — https://advantage.factset.com/hubfs/Website/Resources%20Section/Research%20Desk/Earnings%20Insight/EarningsInsight_082826.pdf
- 저장소 내부: `forecasts/2026/2026-08-08_adbe-eps-beat-fq3-2026_r1.md` (직전 59%, snapshots 없음)

**[미검증]** 표기: 발표일 2026-09-10은 회사 미확정. Investing.com의 ADBE 이력표에 **실제 데이터 오류**가 있다(05/2025 행이 GAAP 실적치 $3.94를 non-GAAP 컨센 $4.97과 대조해 −20.7%로 표시, 발표일도 오기) — 서프라이즈 이력은 SEC 원문 대조본을 사용했다. TipRanks도 Q3 FY25 날짜를 분기 종료일로 오기. Morgan Stanley·Deutsche Bank·BofA 투자의견 변경의 정확한 날짜는 2차 출처 경유 **[부분 미검증]**. "AI-influenced ARR $3B+" 수치는 Adobe 귀속 출처가 없어 **사용하지 않았다**.
