---
forecast_id: 2026-08-31_nvda-dc-beat-2026nov_r1
question_id: nvda-dc-beat-2026nov
question_snapshot: "NVIDIA가 2026-11-18(추정, 과거 패턴) 발표하는 Q3 FY2027 실적에서 Data Center 매출이 발표 직전 컨센서스를 +5% 이상 상회할 확률은?"
timestamp: 2026-08-31 17:10 KST
phase: P1
model: claude-opus-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 17
ci80: [8, 30]
window_end: null
snapshots:
  consensus_dc_revenue: "**NOT FOUND** — Q3 FY27 Data Center 세그먼트 점 추정 컨센서스는 공개 소스에 존재하지 않는다(Visible Alpha·StreetAccount 유료 단말 전용, 발표 당일에야 인용 형태로 공개). r1 선례(2026-07-08)와 동일하게 판정용 스냅샷은 **발표 D-1에 별도 채취**한다"
  consensus_total_revenue: "$108.97B (Yahoo Finance / LSEG, n=41, 채취 2026-08-31 KST)"
  implied_dc_consensus_proxy: "약 $100.8B [미검증 — 자체계산: 총매출 컨센 $108.97B x 최근 2분기 DC 비중 92.5%. 판정 기준 아님]"
  company_guidance: "Q3 FY27 총매출 $108.0B ±2%, 총이익률 74.0% ±50bp. **중국 Data Center compute 매출 0 가정** (2026-08-26 8-K 원문)"
  report_date: "미확정 — NVIDIA 공식 미발표. Yahoo/LSEG·Wall Street Horizon은 2026-11-17(화), TipRanks는 11-25. 회사 관행은 수요일"
market_implied: null
edge: null
sources_count: 13
---

## [0] 질문 검증

**판정 가능성에 구조적 취약점이 있다 — 이를 먼저 기록한다.**

이 질문은 "Data Center 매출이 컨센서스를 +5% 이상 상회"로 판정하는데, **DC 세그먼트 컨센서스는 표준화된 공개 지표가 아니다.** 총매출과 달리 Visible Alpha·StreetAccount 같은 유료 단말에만 존재하고, 발표 당일 언론이 인용하는 형태로만 공개된다. 실제로 과거 8분기 중 2개 분기(FQ4 FY25, FQ1 FY26)는 사후에도 점 추정 컨센서스를 찾을 수 없었다.

더 나쁜 것은 **벤더 간 분산이 임계선을 흔든다**는 점이다. 같은 FQ1 FY27 분기에 대해 Bloomberg 기준 서프라이즈는 +2.3%인데 다른 집계로는 +3.3%로 나온다. 직전 FQ2 FY27도 StreetAccount 기준 +3.12%, Visible Alpha 기준 +3.9%로 갈린다. **5% 임계선에서 벤더 선택만으로 1~2%p가 움직인다.**

r1 선례(`2026-07-08_nvda-dc-beat-2026aug_r1`)가 택한 방식을 따른다 — 총매출 컨센서스를 기록하고, DC 값은 자체계산 proxy로 `[미검증]` 명기하며, **판정용 스냅샷은 발표 D-1에 별도 채취**한다. 다만 해소 시 벤더가 명시되지 않으면 분쟁 소지가 있으므로, 이 질문은 **해소 기준에 벤더·채취시각을 못박는 재정의가 필요하다**고 기록해 둔다(CLAUDE.md 원칙 1).

## [1] Outside View — base rate (anchor: 20%)

DC 매출의 컨센서스 대비 서프라이즈 이력(점 추정 컨센서스가 확인되는 분기만):

| 분기 | 발표 | DC 실적 | 컨센 | 서프라이즈 |
|---|---|---|---|---|
| FQ2 FY25 | 2024-08-28 | $26,272M | $25.24B | +4.09% |
| FQ3 FY25 | 2024-11-20 | $30,771M | $28.82B | **+6.77%** |
| FQ4 FY25 | 2025-02-26 | $35,580M | $33.65B | **+5.74%** |
| FQ2 FY26 | 2025-08-27 | $41,096M | $41.34B | −0.59% (미스) |
| FQ3 FY26 | 2025-11-19 | $51,215M | $49.09B | +4.33% |
| FQ4 FY26 | 2026-02-25 | $62,314M | $60.69B | +2.68% |
| FQ1 FY27 | 2026-05-20 | $75,246M | $73.13B | +2.89% |
| FQ2 FY27 | 2026-08-26 | $89,023M | $86.33B | +3.12% |

**+5% 초과: 8분기 중 2회 = 25%. 최근 5분기 0/5, 최근 6분기 0/6.** 마지막 +5% 초과는 **2024-11-20으로 7분기 전**이다. 평균 +3.63%, 중앙값 +3.61%, 표준편차 약 2.2%p. 최근 4분기는 +2.68~+4.33%의 좁은 밴드에 갇혀 있다.

무조건부 25%를 그대로 쓰면 **2024년 하반기에 몰린 2회를 현 레짐에 투사**하는 것이 된다. 최근 레짐(0/5~0/6)과 무조건부(25%) 사이에서 **anchor 20%**로 출발한다.

## [2] Inside View — 보정 (항목별)

| 증거 | 방향 | 조정 |
|---|---|---|
| **애널리스트 모델의 DC 트래킹 숙련** — 서프라이즈 표준편차가 2.2%p로 좁아졌고 최근 4분기가 +2.7~4.3% 밴드에 고정. 5% 돌파에는 밴드 이탈이 필요 | 하락 | −5%p |
| 가이던스 대비 압축 — 실적/가이던스 초과폭이 FQ2 FY24 +22.8%에서 FQ1 FY27 +4.6%로 축소 | 하락 | −2%p |
| **중국 DC compute 매출 0 가정** — 가이던스 $108.0B가 중국을 전혀 반영하지 않는다. 중국 매출이 조금이라도 인식되면 상방 서프라이즈가 발생하는 **비대칭 옵션** | 상승 | +4%p |
| 압축 서사가 데이터에 없다 — 컨센서스 대비 서프라이즈는 −0.6% → +3.1% → +2.3% → +3.9%로 **오히려 최근 2분기 상승**. "구조적 소멸"이 아니라 "밴드 횡보" | 상승 | +2%p |
| 공급 제약이 바인딩 — CoWoS 완판, 2027 메모리 물량 완판. 수요 초과분이 매출로 전환되지 못하면 서프라이즈 폭이 구조적으로 제한된다 | 하락 | −2%p |
| 벤더 분산 자체가 임계선 리스크 — 5% 경계에서 ±1~2%p가 흔들리며, 이는 확률을 낮추는 쪽으로 작용(정확히 5%를 넘어야 YES) | 하락 | −1%p |
| CFO의 FY2028 +70% 성장 전망(컨센 44%) — 수요 서사는 강하나 이는 연간 전망이지 분기 서프라이즈 폭이 아니다 | 상승 | +1%p |

순 조정 **−3%p** → 17%.

## [3] 분해 트리

| 경로 | 확률 | +5% 초과 조건부 | 기여 |
|---|---|---|---|
| 최근 4분기 밴드(+2~4.5%) 재현 | 0.65 | 0.02 | 1% |
| 중국 DC 매출 일부 인식(가이던스 미반영분) | 0.15 | 0.55 | 8% |
| 공급 해소로 출하 급증 | 0.12 | 0.50 | 6% |
| 수요 둔화·미스 | 0.08 | 0.00 | 0% |
| 중복 보정 | | | +2%p |
| 합계 | | | **17%** |

확률의 대부분이 **중국 변수와 공급 해소**라는 두 개의 비대칭 옵션에서 나온다. 정상 경로로는 사실상 불가능하다 — 최근 4분기 최대치가 +4.33%로 임계선에 못 미친다.

## [4] Premortem — 틀릴 이유 3가지

1. **중국 규제가 완화되는 경우.** 가이던스가 중국 DC compute를 0으로 잡았으므로, 정책 변화로 매출이 인식되면 컨센서스가 이를 반영했는지에 따라 두 자릿수 서프라이즈도 가능하다. 최근 7분기 무돌파를 그대로 외삽하면 이 옵션을 놓친다.
2. **컨센서스 벤더가 낮게 잡히는 경우.** DC 컨센서스는 커버리지가 얇아 총매출 컨센서스보다 분산이 크다. 판정에 쓰이는 벤더가 보수적이면 같은 실적으로도 +5%를 넘길 수 있다. 이는 실적이 아니라 **측정의 문제**다.
3. **반대 방향 — 17%도 높은 경우.** 최근 5분기 0/5에 밴드 상단이 +4.33%다. 밴드 이탈이 일어나지 않는다면 정직한 값은 10% 안팎이다. 내가 중국 옵션에 +4%p를 준 것이 과할 수 있다.

## [5] 최종 출력

- 최종 확률: **17%** (80% CI: 8~30%)
- **핵심 근거 3줄**:
  1. DC 서프라이즈는 최근 4분기 +2.68~4.33%의 좁은 밴드에 갇혀 있고, **마지막 +5% 초과는 7분기 전**이다.
  2. 무조건부 기저율 25%는 2024년 하반기 2회에서 나온 값으로, 최근 레짐(0/5)에 그대로 투사할 수 없다.
  3. 상방은 중국 DC 매출 인식(가이던스 0 가정)이라는 비대칭 옵션이 거의 전부다.
- **관찰 지표 2개**:
  1. **중국향 대미 반도체 정책 변화** — DC compute 수출 허용 신호가 나오면 30% 이상으로 상향.
  2. **발표 D-1 DC 컨센서스 채취값** — $100B를 크게 밑도는 보수적 값이 판정 기준이 되면 +5%p 이상 상향.

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트 통과 전). 덧붙여 이 질문은 **해소 기준에 컨센서스 벤더와 채취 시각이 명시돼 있지 않아 해소 분쟁 위험**이 있다. 판정 전 재정의를 권고한다.

## 출처 목록

- NVIDIA FQ2 FY2027 8-K EX-99.1 (총매출 $96.2B, DC $89.0B, Q3 가이던스 $108.0B ±2%, 중국 DC 0 가정, GM 74.0%) — https://www.sec.gov/Archives/edgar/data/1045810/000104581026000073/q2fy27pr.htm (2026-08-26)
- NVIDIA 실적 보도자료 — https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-second-quarter-fiscal-2027
- NVIDIA Revenue by Market 분기 추이 (DC 세그먼트 실적 시계열) — https://s201.q4cdn.com/141608511/files/doc_financials/2027/Q127/Rev_by_Mkt_Qtrly_Trend_Q127-NEW-v3.pdf
- Yahoo Finance / LSEG NVDA 총매출 컨센서스 ($108.97B, n=41) — https://finance.yahoo.com/quote/NVDA/analysis/ (채취 2026-08-31)
- Bloomberg NVDA 8/27 시총 +$442B — https://www.bloomberg.com/news/articles/2026-08-27/nvidia-adds-442-billion-in-second-biggest-ever-stock-surge
- 저장소 내부 선례: `forecasts/2026/2026-07-08_nvda-dc-beat-2026aug_r1.md` (총매출 컨센 + DC proxy [미검증] + D-1 별도 채취 방식)
- FactSet Earnings Insight 2026-08-28 (비트율 86%/78%/76%, 동률 3%, Q3 부정 가이던스 36%, Mag7 ex-2종목 +4.4%) — https://advantage.factset.com/hubfs/Website/Resources%20Section/Research%20Desk/Earnings%20Insight/EarningsInsight_082826.pdf
- Warsh 잭슨홀 연설 2026-08-28 — https://www.federalreserve.gov/newsevents/speech/warsh20260828a.htm

**[미검증]** 표기: **Q3 FY27 DC 컨센서스는 NOT FOUND**(유료 단말 전용). DC proxy $100.8B는 자체계산이며 판정 기준이 아니다. 발표일은 NVIDIA 미발표이며 서드파티가 11-17과 11-25로 상충한다. 서프라이즈 이력의 컨센서스 값은 StreetAccount 인용 보도 경유로 **[부분 미검증]**이고, FQ2 FY27은 StreetAccount +3.12% / Visible Alpha +3.9%로 출처 간 불일치가 있다. FQ4 FY25·FQ1 FY26 두 분기는 컨센서스 자체가 확인 불가.
