---
forecast_id: 2026-08-29_asml-eps-beat-2026q3_r1
question_id: asml-eps-beat-2026q3
question_snapshot: ASML이 2026-10-14(개장 전, 연간 재무캘린더 관행상 준확정) 발표하는 Q3 2026 실적에서 EPS(ADR USD 기준 집계 컨센 대비)가 발표 직전 컨센서스를 상회할 확률은?
timestamp: 2026-08-29 18:06 KST
phase: P1
model: gpt-5.6-terra
provider: openai
model_snapshot: gpt-5.6-terra
provider_version: reasoning_core_v1
prompt_version: reasoning_core_v1
probability: 57
ci80: [38, 75]
window_end: null
snapshots: {}
market_implied: null
edge: null
research_status: failed
sources_count: 0
method: p1-pipeline/2agents
cost_usd: 0.2045
ensemble_runs: [57]
divergence: null
shadow_extremized: 62
digest_hash: null
digest_inputs: null
pipeline_tier: lite
ml_divergence_pp: null
divergence_note: null
divergence_class: null
research_quality:
  sources: {t1: 1, t2: 0, t3: 4, t4: 0, unknown: 7}
  n_urls: 12
  primary_ratio: 0.083
---

## [0] 질문 검증
기한(2026-10-14 개장 전), 비교대상(발표 직전 D-3 컨센서스), 엄격 상회(동률 NO)는 명확하다. 다만 ASML의 미국 거래 주식은 ADR이 아니라 USD 거래 등록 보통주라는 ASML 공식 설명과 ‘ADR USD’ 문구가 충돌한다. 본 예측은 D-3 스냅샷이 명시할 USD EPS 정의·환산시점을 최종 판정 정의로 조건부 해석한다. 발표일은 ASML 재무캘린더상 2026-10-14이다. [ASML, 2026-02-25, https://ourbrand.asml.com/m/71076aaad607de4d/original/Exhibit%252015.2.pdf; ASML Shares, 2026-02-25, https://www.asml.com/en/en/investors/shares]

## [1] Outside View — base rate (anchor: 65%)
참조 클래스: 참조 클래스는 ‘ASML의 직전 3개 동일 분기(Q3)에서, 당시 공급자 EPS 컨센서스 대비 보고 EPS가 엄격 상회한 경우’다. 관측 표본은 3개뿐이고 모두 단일 민간 컨센서스 계열이어서, 원시 비율 100%를 그대로 쓰지 않고 표본 불확실성·향후 D-3 컨센서스 변경을 반영해 outside-view anchor를 65%로 축소했다. 펀더멘털은 공식 Q3 가이던스와 Q2 실행을 반영했고, 매크로 및 수급은 제공 패키지에 독립적이고 검증 가능한 최신 증거가 없어 별도 보정을 하지 않았다. 데블스 애드버킷 관점은 설치·인수 지연, 수출통제, 컨센서스 상향 위험을 하방 보정에 반영했다.

- Q3 2023: EPS $5.23 대 컨센서스 $5.00으로 상회(1/1). [MarketBeat, 2023-10-18, https://www.marketbeat.com/earnings/reports/2023-10-18-asml-holding-stock/]
- Q3 2024: EPS $5.80 대 컨센서스 $5.24로 상회(2/2). [MarketBeat, 2024-10-15, https://www.marketbeat.com/earnings/reports/2024-10-15-asml-holding-stock/]
- Q3 2025: EPS $6.41 대 컨센서스 $6.27로 상회(3/3). 원시 동일분기 비율은 3/3=100%이나, 해당 컨센서스 데이터의 단일 민간 공급자 한계가 보고돼 있다. [MarketBeat, 2025-10-15, https://www.marketbeat.com/earnings/reports/2025-10-15-asml-holding-stock/; MarketBeat, 2026-08-26, https://www.marketbeat.com/stocks/NASDAQ/ASML/earnings/]

## [2] Inside View — 보정
| 증거 | 방향 | 조정 |
|---|---|---|
| 상방 +4%p: Q2 2026 매출은 €9.326bn, 기본 EPS는 €7.59였고, 회사는 Q3 매출 €11.0–12.0bn·총마진 55–57%를 제시했다. 또한 고객 수요와 공급망·생산·설치 실행력을 근거로 2026년 매출 가이던스를 €43–45bn으로 상향했다. 이는 Q3 가이던스 달성·상단 접근 가능성을 지지한다. [ASML Q2 2026 Results, 2026-07-15, https://www.asml.com/en/news/press-releases/2026/q2-2026-financial-results; ASML Q2 2026 Call Transcript, 2026-07-15, https://ourbrand.asml.com/asset/1fd3908a-0381-47b5-9b69-a3094f656651/2026_07_15-ASML-Transcript-investor-call-Q2-2026.pdf] | ↑ | +4%p |
| 하방 -3%p: 제시된 Q3 매출·마진 가이던스가 이미 구체적이어서, 시장 컨센서스가 가이던스 상단과 높은 마진을 선반영하면 실제 가이던스 부합만으로 EPS 상회가 되지 않을 수 있다. [ASML Q2 2026 Call Transcript, 2026-07-15, https://ourbrand.asml.com/asset/1fd3908a-0381-47b5-9b69-a3094f656651/2026_07_15-ASML-Transcript-investor-call-Q2-2026.pdf] | ↓ | −3%p |
| 하방 -4%p: ASML은 설치·고객 인수검수·출하 및 주문 전환의 지연, 주문 취소·연기, 수출통제, 고객 CAPEX 변동, 단일공급자 부품 위험을 공식 위험요인으로 열거했다. 이들은 매출·EPS를 한 분기 이연시킬 수 있다. [ASML Interim Report, 2026-07-15, https://www.sec.gov/Archives/edgar/data/937966/000162828026048235/statutoryinterimreport20.htm; ASML Q2 2026 Call Transcript, 2026-07-15, https://ourbrand.asml.com/asset/1fd3908a-0381-47b5-9b69-a3094f656651/2026_07_15-ASML-Transcript-investor-call-Q2-2026.pdf] | ↓ | −4%p |
| 하방 -5%p: 판정의 핵심인 2026-10-11 D-3 USD EPS 컨센서스와 환산 기준은 아직 존재하지 않아 확인되지 않았다. 현재 공개된 분기 $11.74 후보는 비공식 단일 공급자 값으로 판정 스냅샷으로 채택할 수 없고, D-3까지 컨센서스 상향 또는 USD 정의 변경이 발생하면 ‘상회’ 문턱이 높아질 수 있다. [Drillr.ai, 2026-08-29, https://drillr.ai/company/ASML/earnings; Boursorama, 2026-08-23, https://www.boursorama.com/cours/consensus/ASML/] | ↓ | −5%p |

## [3] 분해 트리
EPS 상회 = (Q3 실적 실행 수준) AND (그 실행 수준이 D-3 USD 컨센서스를 초과).
├─ 상단 실행: 45% [가이던스 €11.0–12.0bn 및 총마진 55–57% 내에서 상단 쪽 달성이라는 분석적 가정] → 조건부 상회 80% → 36.0%p
├─ 중간 실행: 40% [분석적 가정] → 조건부 상회 45% → 18.0%p
└─ 하단/이연 실행: 15% [설치·인수검수·수출통제 등 공식 리스크를 반영한 분석적 가정] → 조건부 상회 10% → 1.5%p
분해 합계는 약 56%다. 이는 outside-view 65%에서 공식 실행 강점(+4%p)과, 이미 높을 수 있는 컨센서스·운영상 이연·미확정 D-3 기준(-12%p)을 반영한 57%와 거의 일치한다. 가이던스 수치와 위험요인은 ASML Q2 2026 자료 및 SEC 중간보고서에 근거한다. [ASML Q2 2026 Results, 2026-07-15, https://www.asml.com/en/news/press-releases/2026/q2-2026-financial-results; ASML Interim Report, 2026-07-15, https://www.sec.gov/Archives/edgar/data/937966/000162828026048235/statutoryinterimreport20.htm]

## [4] Premortem — 이 예측이 크게 틀렸다면
1. D-3 컨센서스가 가이던스 상단 또는 그 이상으로 상승해, 양호한 실적도 EPS 상회가 아닌 부합/미달로 판정될 수 있다. 현재 판정용 D-3 분기 컨센서스는 확인되지 않았다. [Boursorama, 2026-08-23, https://www.boursorama.com/cours/consensus/ASML/]
2. 고객 인수검수·설치 또는 부품 병목이 발생해 시스템 매출 인식이 다음 분기로 이연되고, 매출과 총마진이 가이던스 하단에 가까워질 수 있다. [ASML Q2 2026 Call Transcript, 2026-07-15, https://ourbrand.asml.com/asset/1fd3908a-0381-47b5-9b69-a3094f656651/2026_07_15-ASML-Transcript-investor-call-Q2-2026.pdf]
3. 수출통제, 주문 취소·연기, 고객 CAPEX 변동 또는 지역·제품 믹스 악화가 AI 수요의 긍정 효과를 상쇄할 수 있다. ASML은 이 위험들을 공식적으로 열거했고, Q3 2025에는 중국 수요가 2026년에 2024~25년보다 크게 낮아질 수 있다고 언급했다. [ASML Interim Report, 2026-07-15, https://www.sec.gov/Archives/edgar/data/937966/000162828026048235/statutoryinterimreport20.htm; ASML Q3 2025 Results, 2025-10-15, https://www.asml.com/en/news/press-releases/2025/q3-2025-financial-results]

## [5] 최종 출력
- **최종 확률: 57%** (80% CI: 38~75%)
- **핵심 근거**:
  1. 동일 Q3의 제공된 과거 표본에서는 2023~2025년 모두 EPS가 당시 컨센서스를 상회했지만, 표본은 3개이고 컨센서스 공급자 한계가 있다. [MarketBeat, 2023-10-18; 2024-10-15; 2025-10-15; 2026-08-26, 위 링크]
  2. ASML의 공식 Q3 가이던스는 매출 €11.0–12.0bn, 총마진 55–57%이며, 회사는 수요·공급망·생산·설치 역량을 근거로 연간 매출 가이던스를 €43–45bn으로 상향했다. [ASML Q2 2026 Results, 2026-07-15, https://www.asml.com/en/news/press-releases/2026/q2-2026-financial-results; ASML Q2 2026 Call Transcript, 2026-07-15, https://ourbrand.asml.com/asset/1fd3908a-0381-47b5-9b69-a3094f656651/2026_07_15-ASML-Transcript-investor-call-Q2-2026.pdf]
  3. 최종 비교 문턱인 D-3 USD EPS 컨센서스·환산 기준이 아직 없고, 설치·인수검수·수출통제·주문 연기 위험이 EPS 상회 여부에 직접적인 하방 비대칭을 만든다. [Drillr.ai, 2026-08-29, https://drillr.ai/company/ASML/earnings; ASML Interim Report, 2026-07-15, https://www.sec.gov/Archives/edgar/data/937966/000162828026048235/statutoryinterimreport20.htm]
- **관찰 지표**:
  1. 2026-10-11 D-3 스냅샷에서 확정되는 공급자명, USD EPS 컨센서스, EUR→USD 환산 방식 및 시점: 현 비공식 $11.74 후보보다 문턱이 유의하게 상승하면 확률을 하향하고, 하락하면 상향한다. [Drillr.ai, 2026-08-29, https://drillr.ai/company/ASML/earnings]
  2. 발표 전 ASML의 설치·고객 인수검수·출하 진행 및 수출통제/주문연기 관련 공식 업데이트: 이연 신호는 하향, 가이던스 상단 실행을 뒷받침하는 신호는 상향한다. [ASML Q2 2026 Call Transcript, 2026-07-15, https://ourbrand.asml.com/asset/1fd3908a-0381-47b5-9b69-a3094f656651/2026_07_15-ASML-Transcript-investor-call-Q2-2026.pdf; ASML Interim Report, 2026-07-15, https://www.sec.gov/Archives/edgar/data/937966/000162828026048235/statutoryinterimreport20.htm]

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전).

## [미검증] 항목
- [미검증] 2026-10-11 D-3 판정용 다중공급자/IBES 분기 USD EPS 컨센서스 및 환산 기준은 미래 시점이라 NOT FOUND다.
- [미검증] ‘ADR USD’는 ASML 공식 주식 구조 설명과 불일치한다. 최종 판정 전에 USD 거래 등록 보통주 EPS인지, 별도 EUR EPS 환산값인지, 환율 시점과 공급자를 고정해야 한다.
- [미검증] 제공 패키지에는 독립적으로 검증 가능한 매크로(금리·유동성) 및 수급(옵션·포지셔닝·플로우) 자료가 없어 이 두 관점의 수치 보정은 적용하지 않았다.

## 리서치 구성
general(출처 0), devil(출처 0) — 증거 부록: `2026-08-29_asml-eps-beat-2026q3_r1_evidence.md`
