---
forecast_id: 2026-08-22_amzn-eps-beat-2026q3_r1
question_id: amzn-eps-beat-2026q3
question_snapshot: Amazon이 2026-10-29(장후 추정) 발표하는 Q3 2026 실적에서 EPS가 발표 직전 컨센서스를 상회할 확률은?
timestamp: 2026-08-22 12:10 KST
phase: P1
model: gpt-5.6-terra
provider: openai
model_snapshot: gpt-5.6-terra
provider_version: reasoning_core_v1
prompt_version: reasoning_core_v1
probability: 72
ci80: [55, 85]
window_end: null
snapshots: {}
market_implied: null
edge: null
research_status: degraded
sources_count: 5
method: p1-pipeline/2agents
cost_usd: 0.1942
ensemble_runs: [72]
divergence: null
shadow_extremized: 84
digest_hash: null
digest_inputs: null
pipeline_tier: lite
ml_divergence_pp: null
divergence_note: null
divergence_class: null
research_quality:
  sources: {t1: 4, t2: 0, t3: 1, t4: 2, unknown: 2}
  n_urls: 9
  primary_ratio: 0.444
---

## [0] 질문 검증
해소 가능: YES는 Amazon Q3 2026의 공식 GAAP 희석 EPS가 실제 발표일 기준 D-3 최종 컨센서스를 초과하는 경우이며, 동률은 NO로 처리한다. 다만 2026-10-29 장후 발표일은 비공식 추정이므로 실제 IR 발표일을 기준으로 D-3를 산정해야 한다. [source: Amazon IR, 2026-07-30; https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx]

## [1] Outside View — base rate (anchor: 88%)
참조 클래스: Amazon의 분기별 GAAP 희석 EPS가 발표 직전 시장 컨센서스를 상회하는 사건. 표본은 제공 자료에서 확인되는 최근 8개 분기(Q3 2024~Q2 2026)이며, Q3 계절성 표본은 제공 자료상 사실상 1건뿐이다.

- 최근 8개 분기(Q3 2024~Q2 2026) EPS 컨센서스 상회는 7/8=87.5%였다. [source: MarketBeat earnings page, 2026-08 초 크롤링; https://www.marketbeat.com/stocks/NASDAQ/AMZN/earnings/]
- 최근 4개 분기(Q3 2025~Q2 2026)는 Q3 2025 beat, Q4 2025 miss, Q1 2026 beat, Q2 2026 beat로 3/4=75.0%였다. [source: MarketBeat earnings page, 2026-08 초 크롤링; https://www.marketbeat.com/stocks/NASDAQ/AMZN/earnings/]
- 제공 자료에서 확인되는 Q3 단일 사례인 Q3 2025는 EPS $1.95가 컨센서스 $1.57를 상회해 1/1=100%였으나, 표본이 1개이므로 독립적·강한 계절성 base rate로 사용하지 않는다. [source: MarketBeat earnings page, 2026-08 초 크롤링; https://www.marketbeat.com/stocks/NASDAQ/AMZN/earnings/]

## [2] Inside View — 보정
| 증거 | 방향 | 조정 |
|---|---|---|
| Q2 2026 GAAP EPS $5.75에는 Anthropic 투자 관련 세전 기타수익 $53.4bn이 포함됐다. Q3 가이던스는 영업이익만 제시하므로 이 비경상적 비영업 이익을 Q3 EPS beat에 외삽하기 어렵다. [source: Amazon SEC Exhibit 99.1, 2026-07-30; https://www.sec.gov/Archives/edgar/data/1018724/000101872426000024/amzn-20260630xex991.htm] | ↓ | −7%p |
| Q4 2025는 EPS $1.95가 컨센서스 $1.97에 못 미쳤다. 최근 8분기 7회 beat라는 높은 anchor가 연속·자동적인 beat를 뜻하지 않는 반례다. [source: MarketBeat earnings page, 2026-08 초 크롤링; https://www.marketbeat.com/stocks/NASDAQ/AMZN/earnings/] | ↓ | −4%p |
| Q3 2026 영업이익 가이던스 중간값 $24.5bn은 Q3 2025의 $17.4bn보다 약 41% 높고, Q2 AWS 매출은 전년 대비 37% 성장했다. 핵심 영업 모멘텀은 EPS 상회 가능성을 지지한다. [source: Amazon IR, 2026-07-30; https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx] | ↑ | +3%p |
| 현재 Q3 EPS 외부 컨센서스 후보는 $1.90, $1.96~$2.03 등으로 제공처별 불일치하며, 판정 기준인 D-3 최종 스냅샷은 아직 없다. 향후 컨센서스 상향이 실제 EPS 개선분을 흡수할 위험을 반영한다. [source: MarketBeat, 2026-08 초; https://www.marketbeat.com/stocks/NASDAQ/AMZN/earnings/] [source: Regarding Semi, 2026-08-20; https://regardingsemi.com/research/company/AMZN] [source: Barchart, 2026-08-19; https://www.barchart.com/stocks/quotes/AMZN/earnings-estimates] | ↓ | −4%p |
| 회사는 Q3 결과의 불확실성으로 환율, 에너지, 수요, 관세 및 메모리칩 공급을 명시했고, 가이던스는 매출 $197.0~202.0bn 및 영업이익 $22.5~26.5bn의 넓은 범위다. [source: Amazon IR, 2026-07-30; https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx] | ↓ | −4%p |

## [3] 분해 트리
EPS beat = (A: 핵심 영업실적이 최종 컨센서스에 필요한 수준을 충족) AND (B: 세금·주식수·비영업 투자평가손익이 EPS를 훼손하지 않음) AND (C: D-3 컨센서스가 실제 실적보다 낮게 유지). 판단 추정으로 A=82%, B=88%, C=90%를 두면 AND 약 65%다. 다만 A와 C는 동일한 사업 모멘텀 및 애널리스트 추정치에 연동돼 단순 곱이 과도하게 비관적일 수 있다. Q3 영업이익 가이던스 중간값의 전년 대비 약 41% 상승은 이 상관된 하방을 일부 완화한다. 따라서 분해값(약 65%)과 anchor 보정값(72%) 사이에서 premortem 후 72%를 채택한다. 가이던스·AWS 수치 출처: Amazon IR, 2026-07-30; https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx

## [4] Premortem — 이 예측이 크게 틀렸다면
1. 핵심 영업이익이 Q3 가이던스 하단($22.5bn)에 머문다. 환율·에너지·수요·관세·메모리 공급이 압박 요인으로 회사가 명시한 리스크다. [source: Amazon IR, 2026-07-30; https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx]
2. Anthropic 관련 평가이익이 Q2처럼 EPS를 끌어올리지 못하거나 평가손실로 전환된다. Q2의 $53.4bn 세전 기타수익은 반복 가능한 영업 성과가 아니다. [source: Amazon SEC Exhibit 99.1, 2026-07-30; https://www.sec.gov/Archives/edgar/data/1018724/000101872426000024/amzn-20260630xex991.htm]
3. 실적 전 애널리스트 컨센서스가 상향돼 실제 EPS 개선을 선반영한다. 현재 제공처별 추정치도 $1.90~$2.03으로 일치하지 않아 D-3 기준선 위험이 남아 있다. [source: MarketBeat, 2026-08 초; https://www.marketbeat.com/stocks/NASDAQ/AMZN/earnings/] [source: Regarding Semi, 2026-08-20; https://regardingsemi.com/research/company/AMZN]

## [5] 최종 출력
- **최종 확률: 72%** (80% CI: 55~85%)
- **핵심 근거**:
  1. 최근 8개 분기 7/8(87.5%) EPS beat라는 강한, 그러나 작은 표본의 outside-view anchor가 있다. [source: MarketBeat earnings page, 2026-08 초 크롤링; https://www.marketbeat.com/stocks/NASDAQ/AMZN/earnings/]
  2. Q3 영업이익 가이던스 중간값 $24.5bn은 전년 Q3의 $17.4bn보다 약 41% 높고, Q2 AWS 매출은 37% 성장해 영업 측면의 완충력을 제공한다. [source: Amazon IR, 2026-07-30; https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx]
  3. 반대로 Q2 EPS의 $53.4bn 세전 기타수익 의존 및 미래 D-3 컨센서스의 미확정성 때문에 87.5% base rate를 그대로 적용하지 않았다. [source: Amazon SEC Exhibit 99.1, 2026-07-30; https://www.sec.gov/Archives/edgar/data/1018724/000101872426000024/amzn-20260630xex991.htm]
- **관찰 지표**:
  1. 실적 전 D-3 최종 EPS 컨센서스의 수준 및 8월 이후 상향·하향 추세: 상향 폭이 크면 YES 확률을 낮추고, 하향이면 높인다. 현재 판정용 D-3 값은 없다. [source: MarketBeat, 2026-08 초; https://www.marketbeat.com/stocks/NASDAQ/AMZN/earnings/]
  2. Q3 중 AWS 성장률·리테일 마진 및 회사 가이던스 관련 공식 업데이트: 영업이익이 $22.5~26.5bn 범위의 어느 쪽에 가까울지가 핵심이다. [source: Amazon IR, 2026-07-30; https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx]

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전).

## [미검증] 항목
- 공식 Q3 2026 발표일은 제공 자료에서 확인되지 않았다. 2026-10-29 장후는 비공식 추정일이다.
- 판정용 D-3 최종 EPS 컨센서스는 미래 시점의 값이므로 NOT FOUND이다.
- 제공 패키지에는 독립적인 장기·동종기업 base rate가 없어, 3개 base-rate 항목 중 2개는 동일 Amazon 표본의 짧은 하위표본이다.

## 리서치 구성
general(출처 0), devil(출처 5) — 증거 부록: `2026-08-22_amzn-eps-beat-2026q3_r1_evidence.md`
