---
forecast_id: 2026-08-31_santa-week-2026_r1
question_id: santa-week-2026
question_snapshot: "S&P500의 2026-12-31 종가가 2026-12-23 종가를 상회할 확률은? (연말 마지막 5거래일: 12/24·28·29·30·31)"
timestamp: 2026-08-31 18:00 KST
phase: P1
model: claude-opus-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 53
ci80: [40, 66]
window_end: null
snapshots:
  definition: "**12월 마지막 5거래일만** (12/24·28·29·30·31). Stock Trader's Almanac의 산타랠리 정의(12월 마지막 5거래일 + 1월 첫 2거래일, 총 7세션)와 **다르다** — 이 차이가 기저율을 79%와 50%로 가른다"
  baseline_close: "2026-12-23 S&P500 종가 (미래 시점 — 판정 시 확정)"
  current_sp500: "7,711.76 (2026-08-28 종가). 사이클 최고 종가 7,798.99 (2026-08-13) 대비 −1.12%"
  nyse_calendar: "2026-12-31 목요일 풀세션 확정"
market_implied: null
edge: null
sources_count: 7
---

## [0] 질문 검증

판정 가능. 다만 **정의 확인이 이 질문의 핵심**이다.

질문은 "12/31 종가 > 12/23 종가", 즉 **12월 마지막 5거래일**만 본다. 널리 인용되는 "산타랠리 79%"는 Stock Trader's Almanac 정의(**12월 마지막 5거래일 + 1월 첫 2거래일**, 총 7세션)의 수치다. 두 정의는 다르며, 아래에서 보듯 기저율이 79%와 50%로 갈린다. 이 구분을 놓치면 25%p 이상 과대평가한다.

## [1] Outside View — base rate (anchor: 53%)

^GSPC 일간 종가 전체 이력(1950-01-03~2026-08-27, n=19,285)으로 두 정의를 각각 재현했다.

| 정의 | 표본 | n | 적중률 | 평균 | t |
|---|---|---|---|---|---|
| 알마낙(5+2) | 1950~2022 | 73 | **79.5%** | +1.319% | 4.95 |
| 알마낙(5+2) | 1990~2025 | 36 | 69.4% | +0.717% | 1.79 |
| **12월 5세션만(본 질문)** | 1950~2025 | 76 | 72.4% | +0.784% | 4.39 |
| **12월 5세션만** | **1990~2025** | 36 | **52.8%** | +0.432% | 1.50 |
| **12월 5세션만** | **2006~2025** | 20 | **50.0%** | +0.291% | 0.82 |

통설 79.5%는 알마낙 정의·1950~2022 표본에서 **소수점까지 정확히 재현된다** — 조작이 아니다. 그러나 **질문 정의로 바꾸면 1990년 이후 52.8%, 2006년 이후 50.0%**로 떨어진다. 1월 2거래일이 리프트의 대부분을 지고 있었다.

시대 분할이 결정적이다 — 12월 5세션 효과는 1950~89년 **90.0%(36/40)**에서 1990년 이후 **52.8%**로 붕괴했다. Hirsch가 1972년 이를 공표한 점을 감안하면 교과서적인 publication-then-decay다.

**랜덤 대비 우위도 없다.** 부트스트랩 20,000회(1990~2025, 동일 기간 무작위 5세션 윈도우 대비): 관측 52.8% vs 랜덤 벤치마크 **57.7%**, 단측 p=0.782 — 우연보다 **못하다**. 참고로 12월 내부의 모든 5세션 윈도우는 61.0%가 양(+)이므로, 12월 자체는 강하지만 **12월의 마지막 5세션은 12월의 다른 5세션보다 못하다**.

최근 5년(12월 5세션 정의): 2021 +0.85% / 2022 +0.45% / 2023 +0.49% / 2024 **−1.55%** / 2025 **−0.93%** → **3/5**.

**anchor 53%** — 1990년 이후 52.8%와 2006년 이후 50.0% 사이.

## [2] Inside View — 보정 (항목별)

| 증거 | 방향 | 조정 |
|---|---|---|
| 12월 전체는 여전히 계절적으로 강함(12월 내 모든 5세션 윈도우 61.0% 양) | 상승 | +2%p |
| 미드텀 선거(11/03) 통과 후 불확실성 해소 국면 — 방향보다 변동성 축소 효과 | 상승 | +1%p |
| 최근 2년 연속 실패(2024 −1.55%, 2025 −0.93%) | 하락 | −1%p |
| 12월 FOMC(12/8~9)가 윈도우 직전에 있고 SEP를 포함 — 매파 서프라이즈 시 연말 약세 유발 가능. 12월 인상 시장가 52% | 하락 | −2%p |
| 연말 세금 손실 매도·리밸런싱이 마지막 주에 집중 | 하락 | 0%p |

순 조정 **0%p** → 53%.

## [3] 분해 트리

| 12월 하순 국면 | 확률 | 5세션 양(+) 조건부 | 기여 |
|---|---|---|---|
| 12월 FOMC 통과 후 안정적 연말 | 0.55 | 0.62 | 34% |
| 매파 FOMC 여파로 변동성 잔존 | 0.25 | 0.42 | 11% |
| 강한 연말 랠리(미드텀 후 계절성 실현) | 0.12 | 0.85 | 10% |
| 급락 국면 | 0.08 | 0.15 | 1% |
| 중복 보정 | | | −3%p |
| 합계 | | | **53%** |

**이 질문에서는 확률을 기저율에서 거의 움직이지 않는 것이 정답이다.** 4개월 앞의 5거래일 방향을 예측할 정보는 사실상 없고, 계절성 앵커 자체가 랜덤 대비 우위가 없다.

## [4] Premortem — 틀릴 이유 3가지

1. **1950~89년 효과가 실재했고 최근 표본이 우연히 나쁜 경우.** 1990년 이후 n=36은 작다. 52.8%와 72.4%(전체 표본)의 차이가 표본 변동일 수 있고, 그렇다면 60% 이상이 맞다.
2. **12월 FOMC가 결정적으로 작용하는 경우.** SEP를 포함한 12/8~9 회의가 윈도우 2주 전이다. 인상 + 매파 점도표면 연말 5거래일이 눌릴 수 있고, 반대로 비둘기 전환이면 랠리가 나온다. 내가 이 이벤트에 −2%p만 준 것이 과소일 수 있다.
3. **반대 방향 — 53%도 높은 경우.** 부트스트랩상 관측 52.8%가 랜덤 57.7%보다 낮았다. 액면 그대로면 오히려 50% 아래를 써야 한다. 다만 그 차이는 통계적으로 유의하지 않아 50% 아래로 내리지는 않았다.

## [5] 최종 출력

- 최종 확률: **53%** (80% CI: 40~66%)
- **핵심 근거 3줄**:
  1. 질문 정의(12월 5세션)의 기저율은 **1990년 이후 52.8%, 2006년 이후 50.0%**이며, 널리 쓰이는 79%는 **다른 정의**(알마낙 5+2)의 수치다.
  2. 이 효과는 1950~89년 90%에서 1990년 이후 52.8%로 붕괴했고, 부트스트랩상 랜덤 5세션(57.7%)보다도 **낮다**(p=0.78).
  3. 4개월 앞 5거래일에 대한 정보가 사실상 없으므로 기저율에서 움직이지 않는 것이 옳다.
- **관찰 지표 2개**:
  1. **12/8~9 FOMC 결과** — 매파 서프라이즈 시 45%로 하향, 비둘기 전환 시 60%로 상향.
  2. **12/23 시점 S&P500의 연초 대비 수익률** — 큰 폭 플러스면 세금 손실 매도 압력이 낮아 소폭 상향.

> **P1 참고 의견 — 자금 결정의 단독 근거 아님** (P3 게이트: 해소 50문항+ & Brier < 0.18 통과 전).

## 출처 목록

- Yahoo Finance ^GSPC 일간 종가 전체 이력(1950-01-03~2026-08-27, n=19,285) — 본 회차가 두 정의를 직접 재현 계산, 재현 가능
- FRED SP500 (2026-08-28 종가 7,711.76, 사이클 최고 7,798.99) — https://fred.stlouisfed.org/series/SP500
- Stock Trader's Almanac 산타랠리 정의 (12월 마지막 5거래일 + 1월 첫 2거래일, Yale Hirsch 1972) — 정의 확인용
- NYSE 휴장·단축거래 캘린더 (2026-12-31 목요일 풀세션) — https://www.nyse.com/markets/hours-calendars
- Morgan Stanley 2026 미드텀 선거 — https://www.morganstanley.com/insights/articles/2026-us-midterm-elections-stock-market-impact
- Kalshi 12월 FOMC 인상 52% (2026-08-31 조회) — https://kalshi.com
- 부트스트랩 검정(20,000회, 1990~2025 무작위 5세션 윈도우 대비): 본 회차 자체 산출, 재현 가능

**[미검증]** 표기: 알마낙 정의의 원 출처(Stock Trader's Almanac 원본)는 유료라 직접 확인하지 못했고, 정의와 인용 수치는 2차 출처 경유 **[부분 미검증]**. 다만 1950~2022 79.5%/평균 +1.319%를 원자료로 재현해 정의의 정확성은 간접 확인했다.
