---
forecast_id: 2026-09-09_adbe-eps-beat-fq3-2026_r3
question_id: adbe-eps-beat-fq3-2026
question_snapshot: "Adobe가 2026-09-10(장후 추정) 발표하는 FQ3 2026 실적에서 조정 EPS가 발표 직전 컨센서스를 상회할 확률은?"
timestamp: 2026-09-09 20:15 KST
phase: P1
model: claude-opus-5 (Claude Code)
prompt_version: reasoning_core_v1
probability: 84
anchor_pct: 85
ci80: [72, 92]
shadow_extremized: 95
window_end: null
snapshots:
  consensus_adjusted_eps: "**$6.079 유지** — r2(2026-08-31)가 고정한 판정 스냅샷을 그대로 쓴다. 판정기준이 '발표 전 마지막 예측 파일 스냅샷 컨센'이므로 이 회차가 기준값을 덮어쓴다는 점을 명시하고, **의도적으로 r2 값을 승계**한다(D-1 재채취로 기준을 흔들지 않기 위함). 2026-09-09 재확인: Zacks $6.08 · TipRanks $6.08(n=29) · Investing.com $6.07 · Yahoo/LSEG $6.09 — 밴드 $6.07~6.09로 r2 값과 실질 동일"
  consensus_wrong_basis: "MarketBeat $4.84(n=3) · Barchart $4.86 · AlphaQuery 계열은 **주식보상만 제외한 제3기준**. Adobe Q2 FY26 조정표로 재확인: GAAP $4.25 → 중간 $4.58 → 회사 non-GAAP $5.96(SBC $1.38 가산). 이 기준으로 대조하면 8분기 전량 beat 가 '4분기 중 2회 miss'로 뒤집힌다 — **사용 금지**"
  company_guidance: "FQ3 non-GAAP EPS **$6.05~6.10**, GAAP EPS $4.40~4.45, 매출 $6.67~6.72B, non-GAAP 영업이익률 약 44.0%, non-GAAP 세율 약 18% (2026-06-11 SEC EX-99.1)"
  report_date: "**확정** — 2026-09-10(목) 미국 장마감 후, 콘퍼런스콜 14:00~15:00 PT. Businesswire 2026-08-31 공지 + 2026-09-08 8-K 재확인. **r2의 '회사 미확정' [미검증] 해소**"
  beat_history_8q: "FQ3'24 +2.65% · FQ4'24 +3.00% · FQ1'25 +2.21% · FQ2'25 +1.81% · FQ3'25 +2.51% · FQ4'25 +1.85% · FQ1'26 +3.24% · FQ2'26 +2.41% → **8/8 beat, miss 0, tie 0, 평균 +2.47%, 최저 +1.81%**"
  guidance_top_beat: "최근 4분기 **자기 가이던스 상단을 평균 +$0.12 초과** (Q3'25 +$0.11 · Q4'25 +$0.10 · Q1'26 +$0.16 · Q2'26 +$0.11). 이번 상단 $6.10 에 적용하면 암묵 실제치 약 $6.22 → 스냅샷 $6.079 대비 +2.3%"
  consensus_creep: "**없음** — Zacks 컨센서스 30일간 $6.08 무변동. 발표 직전 상향으로 바가 올라가는 전형적 miss 셋업이 부재"
  new_since_r2: "① 2026-09-02 8-K: David Wadhwani(President, Creativity & Productivity) 사임, 효력 2026-09-27 — **발표 8일 전** ② 2026-09-03: Anil Chakravarthy 신임 CEO 지명(효력 2026-12-01), 주가 약 -6.7% ③ CFO Dan Durn 2026-06-15 퇴사 → Steve Day 임시 CFO 체제로 **FQ3 전체를 결산** ④ Zacks Rank #3(Hold) → **#4(Sell)**"
  factset_base_rate: "S&P500 Q2 2026 실적 시즌 **87% 상회**(FactSet Earnings Insight 2026-09-04). 5년 평균 78% · 10년 76%. FactSet 은 above/in-line/below 3분류라 tie 를 상회에서 제외 — 본 질문의 동률 NO 규칙과 정합"
market_implied: null
edge: null
sources_count: 16
---

## [0] 질문 검증

판정 가능하다. **이 회차는 D-3 세그먼트 회차(r3)다.**

판정기준은 `YES = 발표 조정 EPS > 발표 전 마지막 예측 파일 스냅샷 컨센`이므로, **이 파일의 스냅샷이 판정 기준값이 된다**. r2(2026-08-31)가 이미 $6.079(Yahoo/LSEG, n=29)로 고정했고, **의도적으로 그 값을 승계한다** — D-1에 재채취해 기준을 흔들면 "결과에 가까워질수록 기준을 옮기는" 모양이 되기 때문이다. 2026-09-09 재확인 결과 $6.07~6.09 밴드로 r2 값과 실질 동일하므로 승계에 손실이 없다.

**기준 정의를 다시 못박는다**: 회사 non-GAAP 정의다. MarketBeat/Barchart 계열의 $4.84~4.86은 주식보상만 제외한 제3기준이며 이 기준으로 대조하면 같은 회사가 8분기 전승에서 4분기 중 2회 miss로 뒤집힌다. r2가 이미 배제했고 여기서도 배제한다.

**r2의 미검증 항목 하나가 해소됐다**: r2는 발표일을 "회사 미확정"으로 남겼는데, Businesswire 2026-08-31 공지와 2026-09-08 8-K로 **2026-09-10 장후 확정**이 확인됐다. 마감을 넘겨 판정 불능이 될 위험이 사라졌다.

## [1] Outside View — base rate (anchor: 85%)

참조 클래스 셋을 병기한다.

| 참조 클래스 | 값 | 비고 |
|---|---|---|
| **Adobe 최근 8분기 non-GAAP EPS beat** | **8/8 = 100%** (Laplace 보정 9/10 = 90%) | 표본이 작아 100%를 그대로 쓰지 않는다 |
| Adobe 최근 4분기 **자기 가이던스 상단 초과** | 4/4, 평균 +$0.12 | 이번 구조에 직접 적용 가능 |
| S&P500 전체 상회율 | 5년 78% · 10년 76% · 직전 분기 87% | 회사 특성 무시 |

**구조가 유리하다는 점이 핵심이다.** 컨센서스 $6.079는 회사 가이던스 밴드($6.05~6.10) **안**에 있고 상단보다 $0.02 낮다. 즉 Adobe는 자기 가이던스 상단 근처만 쳐도 beat한다. 반대로 miss하려면 **가이던스 중간값 아래로 착지**해야 하는데 관측 8분기에 한 번도 없었다.

회사 특유 보정치(90%)와 시장 base rate(78~87%) 사이에서, 가이던스 구조의 유리함을 반영해 anchor를 **85%**로 둔다.

## [2] Inside View — 보정 (항목별)

| 증거 | 방향 | 조정 |
|---|---|---|
| **가이던스 상단 초과 마진이 두껍다** — 최근 4분기 평균 +$0.12. 이번 상단 $6.10 에 적용하면 약 $6.22로 스냅샷 대비 **+2.3%** 여유. 최저 마진(+$0.10)을 써도 $6.20 으로 여전히 beat | 상승 | **+3%p** |
| **컨센서스 creep 부재** — Zacks 30일간 $6.08 무변동. 발표 직전 상향으로 바가 올라가는 전형적 miss 셋업이 없다 | 상승 | **+2%p** |
| **임시 CFO의 첫 완결 분기 (최대 하방)** — Dan Durn 2026-06-15 퇴사, Steve Day 임시 체제가 FQ3 전체를 결산했다. 가이던스 $6.05~6.10 은 **떠나는 CFO가 낸 숫자**이고 마감은 다른 사람이 한다. 신임·임시 CFO의 첫 결산은 조정항목·충당금에서 보수적으로 기우는 구조적 편향이 있다 | 하락 | **−3%p** |
| **경영진 이탈이 발표 직전에 겹쳤다** — Wadhwani(핵심 사업부 수장, 유력 CEO 후보) 사임 발표가 **실적 8일 전**(2026-09-02), CEO 지명이 7일 전(2026-09-03). 퇴직 보상의 non-GAAP 산입 여부는 8-K 수정본 미제출로 **[미검증]** — 통상 주식보상·구조조정비는 non-GAAP 제외라 직접 영향은 제한적일 가능성이 높으나 꼬리 위험 | 하락 | **−2%p** |
| **Zacks Rank #3 → #4(Sell)** — Zacks 프레임워크상 #4/#5는 ESP 기반 beat 예측의 유효 범위 밖이다. 3개월 전(Q2 직전)에는 모델이 beat를 지지했으나 지금은 지지하지 않는다. 다만 Rank는 주가 모멘텀 신호이지 EPS 서프라이즈 예측기가 아니다 | 하락 | **−1%p** |
| **freemium 전환의 근시일 ARR 둔화를 회사가 인정** — 다만 이는 매출·ARR 이야기이지 EPS 서프라이즈와 직결되지 않고, 가이던스에 이미 반영돼 있다 | 하락 | **−1%p** |
| **제공자 분산 위험이 우리 질문에는 무효** — 데블스 애드버킷이 최대 하향 요인으로 지목한 것($4.84~$6.09 스프레드)은 판정 기준을 고정하지 않은 질문에 해당한다. 우리는 r2가 **$6.079·회사 non-GAAP 정의**로 못박았으므로 이 위험이 소거된다 | 중립 | **0%p** |

**85 + 3 + 2 − 3 − 2 − 1 − 1 = 83%** → 아래 분해와 종합해 **84%**.

## [3] 분해 트리

YES = (2026-09-10 에 실제로 발표) AND (회사 non-GAAP EPS > $6.079)

| 조건 | 확률 | 근거 |
|---|---|---|
| 예정대로 발표 | **0.99** | Businesswire 공지 + 9/8 8-K 재확인. 연기 사례 없음 |
| 발표 시 $6.079 초과 | **0.85** | 가이던스 상단 $6.10 대비 역사적 초과분 +$0.10~0.16 → 암묵 $6.20~6.26. miss 하려면 가이던스 **중간값 아래**로 착지해야 하는데 8분기 전례 0. 임시 CFO 첫 결산의 보수 편향을 이 조건부에 반영해 90%(8/8 Laplace)에서 낮춤 |

**P(YES) = 0.99 × 0.85 = 0.842 ≈ 84%**

[2]의 83%와 분해의 84%가 정합한다. **84%**를 채택한다.

**r2(82%) 대비 +2%p.** 근거는 (a) 발표일 확정으로 판정 불능 꼬리 제거, (b) 가이던스 상단 초과 마진 4/4 평균 +$0.12를 실측 확인, (c) 컨센서스 creep 부재 확인. 이 셋이 새로 얹힌 하방(경영진 이탈·Zacks 강등)을 근소하게 상회한다.

## [4] Premortem — 크게 틀릴 이유 3가지

**1. 임시 CFO가 첫 결산을 보수적으로 닫는다.** 가장 그럴듯한 miss 경로다. 떠난 CFO가 낸 가이던스를 후임이 물려받아 마감할 때, 충당금·조정항목 판단을 넉넉히 잡으면 non-GAAP EPS가 가이던스 하단 쪽으로 밀린다. $6.05~6.06 이면 스냅샷 $6.079를 밑돌아 NO다. **가이던스 밴드 안에 미스 구간이 존재한다**는 점이 이 질문의 비대칭이다.

**2. Wadhwani 퇴직 보상이 non-GAAP에 산입된다.** 8-K 수정본이 아직 없어 구조를 모른다. 통상 주식보상은 non-GAAP에서 제외되지만, 현금 퇴직금이나 특수 항목이 영업비용으로 들어가면 EPS를 몇 센트 깎을 수 있다. 마진이 $0.02 수준인 구간에서는 치명적일 수 있다.

**3. 8분기 전승 자체가 표본 편의다.** 100%는 지속 불가능하고 언젠가 끊긴다. 끊기는 분기가 하필 경영진이 셋이나 바뀐 이번일 개연성은 낮지 않다. Laplace 보정으로 90%까지 낮췄지만 그마저 낙관일 수 있다.

세 경로 모두 −7%p로 계상됐다. 하방으로 크게 틀릴 여지는 남아 있고, 상방으로 틀릴 여지(실제가 90%+)는 표본이 이미 8/8이라 제한적이다.

## [5] 데블스 애드버킷 — 반대증거 종합

전담 리서치는 **"항목 1(과거 서프라이즈)과 항목 3(가이던스 대비 컨센서스)은 반증이 아니라 확증으로 나왔다"**고 스스로 보고했다.

- **최대 하향 요인은 판정 모호성이었다** — 제공자별 컨센서스가 $4.84~$6.09로 갈리고, Barchart는 같은 4분기를 "2회 miss"로 기록하는 반면 Zacks·MarketBeat는 "4/4 beat"로 기록한다. **우리 질문은 r2가 기준을 고정해 이 위험을 이미 제거했다** — 고정하지 않은 질문이었다면 해소 불가에 가까웠을 것이다.
- 경영진 이탈 3연타(CFO 6월 · 사업부 수장 9/2 · CEO 지명 9/3)와 임시 CFO 첫 결산은 실재 하방으로 계상했다.
- Zacks Rank #3 → #4 전환. 단 컨센서스 creep 은 **없다**(30일 무변동)는 반대 사실도 함께 확인됐다.
- 사업 역풍: freemium 전환의 ARR 둔화를 회사가 인정, Morgan Stanley Underweight, 주가 YTD −18~24%. 다만 전부 매출·주가 이야기이지 EPS 서프라이즈 직결이 아니다.
- **tie 위험은 사실상 소거됐다**: 스냅샷이 소수 셋째 자리($6.079)이고 발표는 두 자리이므로 정확한 동률이 나올 수 없다. $6.08이면 YES, $6.07이면 NO로 갈린다.

## [6] 최종 출력

- **확률: 84%** · 80% 신뢰구간 **[72, 92]** · r2(82%) 대비 **+2%p**
- 시장내재: Adobe beat 여부를 직접 거래하는 마켓 NOT FOUND. `market_implied` null.

**핵심 근거 3줄**
1. 컨센서스 $6.079가 회사 가이던스 밴드($6.05~6.10) 안에 있고 상단보다 $0.02 낮은데, Adobe는 최근 4분기 자기 가이던스 상단을 평균 **+$0.12** 초과했다 — 역사적 마진을 적용하면 약 $6.22로 2.3% 여유다.
2. 8분기 연속 beat(평균 +2.47%, 최저 +1.81%, miss·tie 0)이고 발표 직전 컨센서스 상향(creep)도 없다.
3. 그러나 임시 CFO가 FQ3 전체를 결산했고 사업부 수장 사임이 발표 8일 전이라, **가이던스 밴드 안에 존재하는 미스 구간($6.05~6.079)** 이 실재한다 — anchor 85%에서 84%로 내렸다.

**확률을 바꿀 관찰 지표 2개**
1. **Wadhwani 퇴직 보상 8-K 수정본** — 현금 퇴직금이 non-GAAP 영업비용에 산입되는 구조면 하향(−3~5%p). 주식보상 위주면 무영향.
2. **발표 당일 non-GAAP 세율·희석주식수** — 가이던스는 세율 약 18%, 주식수 약 395M을 가정한다. 세율이 20%+로 나오면 EPS 몇 센트가 깎여 $6.079 마진을 잠식한다.

---

**P1 참고 의견 — 자금 결정의 단독 근거가 아닙니다.** (P3 게이트 미통과: 해소 7문항 / 50, Brier 0.1599)

## 출처

1. Adobe Q2 FY2026 8-K EX-99.1 (2026-06-11) — FQ3 가이던스·GAAP→non-GAAP 조정표 https://www.sec.gov/Archives/edgar/data/796343/000079634326000109/adbeex991q226.htm
2. Adobe 8-K (2026-09-02) — Wadhwani 사임, 보상 정보 4영업일 내 수정 제출 예정 https://www.sec.gov/Archives/edgar/data/0000796343/000079634326000144/adbe-20260902.htm
3. Adobe 실적 발표일 공지 (2026-08-31) https://www.businesswire.com/news/home/20260831054310/en/Adobe-to-Announce-Q3-FY2026-Earnings-Results-on-Sept.-10-2026
4. Adobe 8-K (2026-09-08) — 발표일 재확인 https://www.sec.gov/Archives/edgar/data/0000796343/000079634326000144/adbeex9918-k9826.htm
5. Adobe 뉴스룸 — Chakravarthy 신임 CEO (2026-09-03) https://news.adobe.com/news/2026/09/adobe-announces-anil-chakravarthy-to-become-president-and-ceo
6. CNBC — CEO 전환·주가 반응 (2026-09-03) https://www.cnbc.com/2026/09/03/adobe-anil-chakravarthy-ceo.html
7. Bloomberg — CFO Dan Durn 이탈 (2026-06-11) https://www.bloomberg.com/news/articles/2026-06-11/adobe-s-cfo-departs-leaving-company-seeking-top-executives [헤드라인 확인]
8. CFO Dive — CFO 공백·Steve Day 임시 https://www.cfodive.com/news/adobe-cfo-leadership-gap-marvell-amid-ceo-search-ai/822849/
9. Zacks 프리뷰 (Globe and Mail 경유, 2026-09-08) — 컨센서스 $6.08, Rank #4, 30일 무변동 https://www.theglobeandmail.com/investing/markets/stocks/ADBE/pressreleases/4497362/adobe-before-q3-earnings-should-you-hold-or-fold-the-adbe-stock/
10. TipRanks — 실적 이력·컨센서스 https://www.tipranks.com/stocks/adbe/earnings
11. Investing.com — 실적 이력·컨센서스 https://www.investing.com/equities/adobe-sys-inc-earnings
12. MarketBeat — 실적 이력(회사 non-GAAP) 및 제3기준 추정표 병존 https://www.marketbeat.com/stocks/NASDAQ/ADBE/earnings/
13. Barchart/Yahoo (2026-07-27) — 제3기준으로 "4분기 중 2회 miss" 기술, 판정 기준 분산의 직접 증거 https://finance.yahoo.com/markets/stocks/articles/expect-adobe-q3-2026-earnings-123159830.html
14. AlphaStreet FQ3 프리뷰 — 컨센서스 $6.09 https://news.alphastreet.com/adobe-adbe-q3-2026-preview-eps-est-6-09-reports-september-10/
15. FactSet Earnings Insight (2026-09-04) — Q2 2026 상회율 87%, 5년 78% https://insight.factset.com/sp-500-earnings-season-update-august-7-2026
16. Zacks (2026-06-04) — Q2 직전 Rank #3 + ESP 조합 https://finance.yahoo.com/markets/stocks/articles/adobe-systems-adbe-reports-next-140001653.html
